# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
"""
ZEN70 结构化日志公共模块。

统一 JSON 格式（含 timestamp/level/caller/message/X-Request-ID），
供 redis_client、sentinel、config-compiler、bootstrap 等复用。
"""

from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, Optional


class JsonFormatter(logging.Formatter):
    """
    单行 JSON 日志格式化器；含 timestamp(UTC)、level、logger、caller、message、X-Request-ID。
    对齐 Loki 采集标准。
    """

    def format(self, record: logging.LogRecord) -> str:
        log_obj: Dict[str, Any] = {
            "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "level": record.levelname,
            "logger": record.name,
            "caller": f"{record.pathname}:{record.lineno}",
            "message": record.getMessage(),
            "X-Request-ID": getattr(record, "request_id", None),
        }
        if record.exc_info:
            log_obj["exception"] = self.formatException(record.exc_info)
        return json.dumps(log_obj, ensure_ascii=False)


def get_logger(name: str, request_id: Optional[str] = None) -> logging.LoggerAdapter:
    """返回带 request_id 的 LoggerAdapter，用于结构化日志。"""
    base = logging.getLogger(name)
    base.setLevel(logging.INFO)
    if not base.handlers:
        h = logging.StreamHandler()
        h.setFormatter(JsonFormatter())
        base.addHandler(h)
    rid = request_id or str(uuid.uuid4())
    return logging.LoggerAdapter(base, {"request_id": rid})
