"""
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.

ZEN70 极客家族留言板 API 路由 (Feature M8)
"""

from __future__ import annotations

import json
from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from backend.api.deps import get_db, get_redis
from backend.core.jwt import get_current_user
from backend.core.redis_client import RedisClient, CHANNEL_BOARD_EVENTS
from backend.models.board import FamilyMessage
from backend.models.user import User

router = APIRouter(prefix="/api/v1/board", tags=["Family Board"])


# --- Pydantic Models ---
class AuthorInfo(BaseModel):
    id: int
    username: str
    display_name: Optional[str] = None
    role: str


class BoardMessageCreate(BaseModel):
    content: str = Field(..., max_length=2000, description="留言正文内容")
    meta_info: Optional[dict] = Field(default=None, description="附加元数据")
    is_pinned: bool = False


class BoardMessageResponse(BaseModel):
    id: UUID
    content: str
    meta_info: Optional[dict] = None
    is_pinned: bool
    created_at: str
    author: AuthorInfo

    class Config:
        from_attributes = True


# --- Endpoints ---

@router.get(
    "",
    response_model=List[BoardMessageResponse],
    summary="获取当前租户的所有留言记录"
)
async def get_board_messages(
    limit: int = Query(50, gt=0, le=100),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
) -> List[BoardMessageResponse]:
    """
    按时间倒序获取家族信标流。严格遵守 RLS 租户级硬隔离。
    """
    stmt = (
        select(FamilyMessage)
        .where(FamilyMessage.tenant_id == current_user.tenant_id)
        .order_by(desc(FamilyMessage.is_pinned), desc(FamilyMessage.created_at))
        .offset(offset)
        .limit(limit)
    )
    result = await db.execute(stmt)
    messages = result.scalars().all()
    
    # 转换为 response (日期强制 isoformat)
    resp = []
    for m in messages:
        resp.append(BoardMessageResponse(
            id=m.id,
            content=m.content,
            meta_info=m.meta_info,
            is_pinned=m.is_pinned,
            created_at=m.created_at.isoformat(),
            author=AuthorInfo(
                id=m.author.id,
                username=m.author.username,
                display_name=m.author.display_name,
                role=m.author.role
            )
        ))
    return resp


@router.post(
    "",
    response_model=BoardMessageResponse,
    status_code=status.HTTP_201_CREATED,
    summary="发布新家族留言"
)
async def create_board_message(
    payload: BoardMessageCreate,
    x_idempotency_key: Optional[str] = None,  # TODO: 法典要求的防抖锁可以通过 router dependency 实施，此处简化
    db: AsyncSession = Depends(get_db),
    redis: RedisClient | None = Depends(get_redis),
    current_user: User = Depends(get_current_user)
) -> BoardMessageResponse:
    """
    发布一条新的家族留言。操作成功后，向 Redis CHANNEL_BOARD_EVENTS 广播 SSE 事件。
    """
    new_msg = FamilyMessage(
        tenant_id=current_user.tenant_id,
        author_id=current_user.id,
        content=payload.content,
        meta_info=payload.meta_info,
        is_pinned=payload.is_pinned
    )
    db.add(new_msg)
    await db.commit()
    await db.refresh(new_msg)
    # 因为 refresh 并不一定能把 relationship (author) 完美装载（虽然我们在 model 里加了 lazy='joined'，但新建对象时未查询关联），
    # 若直接返回会缺失 author，这里我们强制注入 current_user 的信息给 frontend
    
    # 广播 SSE 事件，驱动极速无感刷新
    if redis:
        try:
            event_payload = json.dumps({
                "action": "new_message",
                "message_id": str(new_msg.id),
                "author": current_user.display_name or current_user.username
            })
            pubsub = redis.pubsub()
            await redis._client.publish(CHANNEL_BOARD_EVENTS, event_payload)
        except Exception:
            pass # V2.0: redis 连接抖动时不影响落盘

    return BoardMessageResponse(
        id=new_msg.id,
        content=new_msg.content,
        meta_info=new_msg.meta_info,
        is_pinned=new_msg.is_pinned,
        created_at=new_msg.created_at.isoformat(),
        author=AuthorInfo(
            id=current_user.id,
            username=current_user.username,
            display_name=current_user.display_name,
            role=current_user.role
        )
    )


@router.delete(
    "/{msg_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="删除家族留言"
)
async def delete_board_message(
    msg_id: UUID,
    db: AsyncSession = Depends(get_db),
    redis: RedisClient | None = Depends(get_redis),
    current_user: User = Depends(get_current_user)
):
    """
    删除一条留言（仅本人或 admin 可删）。
    """
    stmt = select(FamilyMessage).where(FamilyMessage.id == msg_id, FamilyMessage.tenant_id == current_user.tenant_id)
    result = await db.execute(stmt)
    msg = result.scalar_one_or_none()
    
    if not msg:
        raise HTTPException(status_code=404, detail="Message not found")
        
    if msg.author_id != current_user.id and current_user.role != "admin":
        raise HTTPException(status_code=403, detail="Permission denied to delete this message")
        
    await db.delete(msg)
    await db.commit()
    
    if redis:
        try:
            event_payload = json.dumps({
                "action": "delete_message",
                "message_id": str(msg_id)
            })
            pubsub = redis.pubsub()
            await redis._client.publish(CHANNEL_BOARD_EVENTS, event_payload)
        except Exception:
            pass

    return
