# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
"""
ZEN70 核心 API 网关 (FastAPI)。
提供 /api/v1/capabilities、/api/v1/events(SSE)、/health；
统一错误码、X-Request-ID、结构化日志、优雅启停。
"""

from __future__ import annotations

import asyncio
import re
import time
import uuid
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from fastapi import HTTPException

from backend.api import routes
from backend.api import auth as auth_router
from backend.api import assets as assets_router
from backend.api import media as media_router
from backend.api import settings as settings_router
from backend.api import search as search_router
from backend.api import iot as iot_router
from backend.api import portability as portability_router
from backend.api import push as push_router
from backend.worker import alert_manager as alert_router
from backend.api.deps import get_redis, get_settings
from backend.api.models import ErrorResponse, HealthResponse
from backend.core.redis_client import RedisClient, get_logger

# -------------------- 日志 --------------------
logger = get_logger("api")


# -------------------- 健康检查：PostgreSQL 可达性（仅 TCP） --------------------
async def _check_postgres_async(dsn: str | None) -> str:
    if not dsn or not dsn.strip():
        return "not_configured"
    try:
        m = re.search(r"@([^:/]+)(?::(\d+))?", dsn)
        if not m:
            return "error"
        host, port_str = m.group(1), m.group(2)
        port = int(port_str) if port_str else 5432
        await asyncio.wait_for(asyncio.open_connection(host, port), timeout=2.0)
        return "ok"
    except Exception:
        return "error"


# -------------------- Lifespan --------------------
async def _connect_redis_with_retry(settings: dict, max_attempts: int = 5) -> RedisClient | None:
    """Redis 连接，指数退避重试。"""
    backoff = [1, 2, 4, 8, 16]
    for attempt in range(max_attempts):
        client = RedisClient(
            host=settings["redis_host"],
            port=settings["redis_port"],
            password=settings["redis_password"],
            db=settings["redis_db"],
        )
        try:
            await asyncio.wait_for(client.connect(), timeout=10.0)
            return client
        except asyncio.TimeoutError:
            logger.warning(f"Redis connect timeout, attempt {attempt + 1}/{max_attempts}")
        except Exception as e:
            logger.warning(f"Redis connect attempt {attempt + 1}/{max_attempts} failed: {e}")
        if attempt < max_attempts - 1:
            await asyncio.sleep(backoff[min(attempt, len(backoff) - 1)])
    return None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """启动时创建 Redis 连接并注入 app.state；关闭时释放。"""
    logger.info("Starting API server")
    settings = get_settings()
    app.state.redis = await _connect_redis_with_retry(settings)
    if app.state.redis is None:
        logger.error("Redis unavailable after retries; API will run with degraded capabilities")
    yield
    logger.info("Shutting down API server")
    if getattr(app.state, "redis", None) is not None:
        await app.state.redis.close()
        app.state.redis = None


# -------------------- App --------------------
app = FastAPI(
    title="ZEN70 API",
    version="1.56.0",
    lifespan=lifespan,
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

settings = get_settings()
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings["cors_origins"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def add_request_id_and_log(request: Request, call_next):
    """注入 X-Request-ID、响应头、请求摘要日志。"""
    request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())
    request.state.request_id = request_id
    start = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Process-Time"] = f"{duration:.3f}"
    logger.info(
        f"{request.method} {request.url.path} {response.status_code} {duration:.3f}s",
        extra={"request_id": request_id, "method": request.method, "path": request.url.path, "status_code": response.status_code, "duration": duration},
    )
    return response


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """HTTPException 若 detail 为含 code 的 dict，则响应体为统一错误码格式。"""
    if isinstance(exc.detail, dict) and "code" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """422 校验错误转为统一错误码。"""
    request_id = getattr(request.state, "request_id", "unknown")
    return JSONResponse(
        status_code=422,
        content=ErrorResponse(
            code="ZEN-VAL-422",
            message="Validation error",
            recovery_hint="Check request payload and retry",
            details={"request_id": request_id, "errors": exc.errors()},
        ).model_dump(),
    )


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """未捕获异常转为 ZEN-INT-5000。"""
    request_id = getattr(request.state, "request_id", "unknown")
    logger.error(f"Unhandled exception: {exc}", exc_info=True, extra={"request_id": request_id})
    return JSONResponse(
        status_code=500,
        content=ErrorResponse(
            code="ZEN-INT-5000",
            message="Internal server error",
            recovery_hint="Retry later or contact administrator",
            details={"request_id": request_id},
        ).model_dump(),
    )


@app.get("/health", response_model=HealthResponse)
async def health_check(request: Request):
    """健康检查：服务状态及 Redis、PostgreSQL 依赖（带超时，避免慢依赖拖死）。"""
    redis_client: RedisClient | None = getattr(request.app.state, "redis", None)
    services: dict[str, str] = {}
    if redis_client:
        try:
            ok = await asyncio.wait_for(redis_client.ping(), timeout=2.0)
            services["redis"] = "ok" if ok else "error"
        except asyncio.TimeoutError:
            services["redis"] = "timeout"
        except Exception:
            services["redis"] = "error"
    else:
        services["redis"] = "error"
    try:
        postgres_dsn = get_settings().get("postgres_dsn")
        services["postgres"] = await asyncio.wait_for(_check_postgres_async(postgres_dsn), timeout=2.0)
    except asyncio.TimeoutError:
        services["postgres"] = "timeout"
    status = "healthy" if services.get("redis") == "ok" else "unhealthy"
    return HealthResponse(status=status, version="1.56.0", services=services)


app.include_router(routes.router)
app.include_router(auth_router.router)
app.include_router(assets_router.router)
app.include_router(media_router.router)
app.include_router(settings_router.router)
app.include_router(search_router.router)
app.include_router(iot_router.router)
app.include_router(portability_router.router)
app.include_router(alert_router.router)
app.include_router(push_router.router, prefix="/api/v1/auth/push", tags=["Web Push"])
