#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
#
# ZEN70 核心 API 网关 (FastAPI)。
# 
# 红线合规：FastAPI + Pydantic v2 | SSE 心跳 45s cancel | LRU 缓存 TTL 30s |
# 统一错误码含 recovery_hint | PENDING_MAINTENANCE 熔断 503 | 纯动态 UPS 熔断
from __future__ import annotations

import asyncio
import os
import time
import uuid
import sqlite3
import hashlib
from pathlib import Path
from contextlib import asynccontextmanager
from typing import Any, Dict
import logging
import json
import httpx
from datetime import datetime, timezone

# 阶段八：任务0 - 全局时间线对齐 (Global Time Alignment)
class UTCFormatter(logging.Formatter):
    
    def formatTime(self, record, datefmt=None):
        dt = datetime.fromtimestamp(record.created, tz=timezone.utc)
        if datefmt:
            return dt.strftime(datefmt)
        return dt.isoformat(timespec='milliseconds')

_log_fmt = logging.Formatter("%(asctime)s [%(levelname)s] [%(trace_id)s] [GATEWAY] %(message)s")
__utc_fmt = UTCFormatter("%(asctime)s [%(levelname)s] [%(trace_id)s] [GATEWAY] %(message)s")

# 配置根 Logger
logging.basicConfig(level=logging.INFO)
root_logger = logging.getLogger()
for handler in root_logger.handlers:
    handler.setFormatter(__utc_fmt)

logger = logging.getLogger(__name__)

from fastapi import FastAPI, Request, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError, HTTPException
from backend.api.deps import get_current_user_optional
from pydantic import BaseModel, Field
from prometheus_client import make_asgi_app

from backend.core.metrics import metrics_middleware
from starlette.middleware.base import BaseHTTPMiddleware
import subprocess
from pathlib import Path
from sse_starlette.sse import EventSourceResponse
import contextvars

# 阶段八：任务1 - API 边缘层注射 TraceID (使用 contextvars 避免并发污染)
_trace_id_ctx: contextvars.ContextVar[str] = contextvars.ContextVar("trace_id", default="NO-TRACE")

old_factory = logging.getLogRecordFactory()
def record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    setattr(record, "trace_id", _trace_id_ctx.get())
    return record
logging.setLogRecordFactory(record_factory)

class TraceIDMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # 如果上游（如 Caddy/Cloudflare）已传，则复用；否则生成新 UUID4
        trace_id = request.headers.get("X-Trace-Id") or uuid.uuid4().hex
        request.state.trace_id = trace_id
        
        # 将 trace_id 绑定到安全的协程上下文
        token = _trace_id_ctx.set(trace_id)
        try:
            response = await call_next(request)
            response.headers["X-Trace-Id"] = trace_id
            return response
        finally:
            _trace_id_ctx.reset(token)

try:
    import redis.asyncio as redis
except ImportError:
    redis = None  # type: ignore

# -------------------- 常量（法典 2.1.1）--------------------
REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_USER = os.getenv("REDIS_USER", "default")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD") or None
TOPOLOGY_KEY_PREFIX = "zen70:topology:"
LRU_CACHE_TTL = 30
SSE_PING_TIMEOUT = 45  # 连续 45s 未收 Ping 必须 cancel() 释放 FD
_sse_last_ping: Dict[str, float] = {}

# -------------------- Pydantic 模型（法典 2.1.1 建议7）--------------------


class ErrorResponse(BaseModel):
    """统一错误码契约：废除模糊 500，含 recovery_hint。"""
    code: str = Field(..., description="ZEN-xxx 错误码")
    message: str = Field(..., description="用户可读说明")
    recovery_hint: str = Field(..., description="恢复建议，供前端渲染操作按钮")
    details: Dict[str, Any] = Field(default_factory=dict)


class CapabilityItem(BaseModel):
    """单个能力：status=online 则 enabled，PENDING_MAINTENANCE 则 disabled。"""
    status: str = Field(..., description="online | pending_maintenance | unknown")
    enabled: bool = Field(..., description="是否可交互")
    endpoint: str | None = Field(None, description="绑定的内网或外网端点")
    models: list[str] | None = Field(None, description="携带的具体模型数组")
    reason: str | None = Field(None, description="状态或异常附加说明")


# -------------------- 全局状态：LRU 缓存（法典 2.1.1 CAP 妥协）--------------------
_lru_cache: Dict[str, Any] = {}
_lru_ts: float = 0.0
_redis_available: bool = True

# 法典 3.2.5：冷启动 Redis 失联时的全域安全模式（All-OFF），放行基础 API 并向前端告警
ALL_OFF_MATRIX: Dict[str, CapabilityItem] = {
    "ups": CapabilityItem(status="offline", enabled=False, reason="总线未就绪"),
    "network": CapabilityItem(status="offline", enabled=False, reason="总线未就绪"),
    "gpu": CapabilityItem(status="offline", enabled=False, reason="总线未就绪"),
}


async def _get_redis() -> "redis.Redis | None":
    if redis is None:
        return None
    return redis.Redis(
        host=REDIS_HOST,
        port=int(REDIS_PORT),
        username=REDIS_USER if REDIS_PASSWORD else None,
        password=REDIS_PASSWORD,
        db=0,
        decode_responses=True,
        socket_connect_timeout=3,
    )


async def _fetch_topology_from_redis(r: "redis.Redis") -> Dict[str, str]:
    """从 Redis 读取 zen70:topology:* 探针写入的状态。"""
    try:
        keys = await r.keys(f"{TOPOLOGY_KEY_PREFIX}*")
        result: Dict[str, str] = {}
        for key in keys:
            cap = key.replace(TOPOLOGY_KEY_PREFIX, "")
            val = await r.get(key)
            result[cap] = (val or "unknown").strip()
        return result
    except Exception:
        return {}


async def get_capabilities_matrix(request: Request) -> Dict[str, CapabilityItem]:
    """
    获取能力矩阵。法典 2.1.1：LRU 缓存 TTL≤30s，Redis 宕机用缓存兜底（悲观静默），
    恢复后清空脏缓存重拉。
    """
    global _lru_cache, _lru_ts, _redis_available
    # 使用全局以支持缓存写回
    now = time.time()

    r = await _get_redis()
    if r is None:
        if now - _lru_ts <= LRU_CACHE_TTL and _lru_cache:
            if hasattr(request.state, "bus_ready"):
                request.state.bus_ready = True
            return _lru_cache.get("matrix", {})
        if hasattr(request.state, "bus_ready"):
            request.state.bus_ready = False
        return ALL_OFF_MATRIX

    try:
        topology = await _fetch_topology_from_redis(r)
        await r.aclose()
        redis_was_down = not _redis_available
        _redis_available = True
    except Exception:
        _redis_available = False
        if now - _lru_ts <= LRU_CACHE_TTL and _lru_cache:
            return _lru_cache.get("matrix", {})
        if hasattr(request.state, "bus_ready"):
            request.state.bus_ready = False
        return ALL_OFF_MATRIX

    # Redis 恢复后若之前不可用，清空脏缓存（法典 2.1.1 强制红线）
    if redis_was_down and topology:
        _lru_cache.clear()

    matrix: Dict[str, CapabilityItem] = {}
    for cap, status in topology.items():
        is_pending = status == "PENDING_MAINTENANCE"
        matrix[cap] = CapabilityItem(
            status=status.lower().replace("_", "-"),
            enabled=not is_pending,
        )

    # 法典 1.2: 系统状态由 compiler.py 编译至 .env，由后端读取注入 UI。
    # 彻底解耦面板硬编码，让 Restic 引擎配置无感映射到前端开关。
    backup_enabled = os.getenv("BACKUP_ENABLED", "true").lower() == "true"
    matrix["容灾备份"] = CapabilityItem(
            status="online" if backup_enabled else "offline",
            enabled=True,
            models=["Restic引擎", "S3对象锁定"],
            reason="安全级别: Critical" if backup_enabled else "已被系统基线 (system.yaml) 拦截关闭",
    )
    
    # [AbsDecoupling Audit] Injecting mock test service to verify Vue v-for dynamic rendering.
    matrix["Ghost Protocol Test"] = CapabilityItem(
            status="online",
            enabled=True,
            models=["Mock_AI_V1"],
            reason="Absolute Decoupling Verification",
    )

    _lru_cache = {"matrix": matrix, "topology_raw": topology}
    _lru_ts = now
    if hasattr(request.state, "bus_ready"):
        request.state.bus_ready = True
    return matrix


def _check_capability_pending(matrix: Dict[str, CapabilityItem], capability: str) -> bool:
    """若能力处于 PENDING_MAINTENANCE，返回 True（需熔断）。"""
    item = matrix.get(capability)
    if not item:
        return False
    return not item.enabled


# -------------------- 熔断 503（法典 2.3.2）--------------------
def raise_503_if_pending(capability: str, matrix: Dict[str, CapabilityItem]) -> None:
    """熔断大闸：PENDING_MAINTENANCE 时抛 503。"""
    if _check_capability_pending(matrix, capability):
        raise HTTPException(
            status_code=503,
            detail=ErrorResponse(
                code="ZEN-STOR-1001",
                message="硬件维护中，请求已熔断",
                recovery_hint="请检查物理连接，探针重连后自动恢复。",
                details={"capability": capability},
            ).model_dump(),
        )


# -------------------- Bit-Rot 巡检（法典 3.2.3）--------------------
# 路径解耦：BITROT_SCAN_DIRS 仅来自 .env（compiler 从 system.yaml capabilities.storage 等写入）
BITROT_DB_PATH = Path("/app/data/bitrot.db") if Path("/app").exists() else Path("bitrot.db")
_bitrot_dirs_raw = os.getenv("BITROT_SCAN_DIRS", "")
BITROT_SCAN_DIRS = [p.strip() for p in _bitrot_dirs_raw.split(",") if p.strip()]

def _init_bitrot_db():
    conn = sqlite3.connect(BITROT_DB_PATH)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS file_hashes (
            filepath TEXT PRIMARY KEY,
            sha256 TEXT NOT NULL,
            last_checked REAL NOT NULL
        )
    ''')
    conn.commit()
    conn.close()

async def bitrot_worker():
    """法典 3.2.3: 后台巡检冷数据，低优先级 hashing。仅启动时和每24小时运行。"""
    try:
        # 给系统启动留出缓冲期
        await asyncio.sleep(60)
        _init_bitrot_db()
        
        while True:
            # 法典要求：利用低优先级检测。此处简单模拟，避免高频 I/O。
            conn = sqlite3.connect(BITROT_DB_PATH)
            cursor = conn.cursor()
            now = time.time()
            
            for directory in BITROT_SCAN_DIRS:
                dir_path = Path(directory)
                if not dir_path.exists():
                    continue
                for root, _, files in os.walk(dir_path):
                    for file in files:
                        filepath = Path(root) / file
                        if not filepath.exists() or not filepath.is_file():
                            continue
                            
                        # 低优先级哈希计算 (避免阻塞事件循环，使用 thread_pool)
                        def compute_hash() -> str:
                            sha256_hash = hashlib.sha256()
                            with open(filepath, "rb") as f:
                                # 每次读取 4K，防止大文件 OOM
                                for byte_block in iter(lambda: f.read(4096), b""):
                                    sha256_hash.update(byte_block)
                            return sha256_hash.hexdigest()
                            
                        try:
                            file_hash = await asyncio.to_thread(compute_hash)
                            cursor.execute(
                                "SELECT sha256 FROM file_hashes WHERE filepath = ?", 
                                (str(filepath),)
                            )
                            row = cursor.fetchone()
                            
                            if row is None:
                                # 首次记录基线
                                cursor.execute(
                                    "INSERT INTO file_hashes (filepath, sha256, last_checked) VALUES (?, ?, ?)",
                                    (str(filepath), file_hash, now)
                                )
                            else:
                                if row[0] != file_hash:
                                    logger.error(
                                        f"重大警告: 侦测到静默数据腐败 (Bit-Rot)! "
                                        f"文件: {filepath} \n"
                                        f"原哈希: {row[0]} \n"
                                        f"现哈希: {file_hash}"
                                    )
                                    # TODO: 接入系统告警总线
                                else:
                                    cursor.execute(
                                        "UPDATE file_hashes SET last_checked = ? WHERE filepath = ?",
                                        (now, str(filepath))
                                    )
                            conn.commit()
                            # 每个文件计算后主动让出事件循环并延时，绝对防霸占 CPU
                            await asyncio.sleep(0.5)
                        except Exception as e:
                            pass
            
            conn.close()
            # 24 小时巡检一次
            await asyncio.sleep(86400)
    except asyncio.CancelledError:
        pass


# -------------------- SRE 探针 (法典 3.6: Readiness & Liveness) --------------------
# 解耦依赖: 外部配置需要监控的微服务 healthz 端点
_microservices_health_urls: Dict[str, str] = {}
try:
    urls_raw = os.getenv("MICROSERVICE_HEALTH_URLS", "{}")
    if urls_raw: _microservices_health_urls = json.loads(urls_raw)
except Exception: pass

# 状态字典
service_readiness: Dict[str, bool] = {}
_service_liveness_fails: Dict[str, int] = {}

async def health_probe_worker():
    """定期执行微服务探针: Liveness 连续失败 3 次强杀重启; Readiness 封锁进站流量。"""
    await asyncio.sleep(5)  # 启动延时
    async with httpx.AsyncClient(timeout=2.0) as client:
        while True:
            r = await _get_redis()
            
            for svc_name, health_url in _microservices_health_urls.items():
                is_ok = False
                try:
                    resp = await client.get(health_url)
                    if resp.status_code == 200:
                        is_ok = True
                except Exception:
                    pass
                
                if is_ok:
                    service_readiness[svc_name] = True
                    _service_liveness_fails[svc_name] = 0
                else:
                    service_readiness[svc_name] = False
                    _service_liveness_fails[svc_name] = _service_liveness_fails.get(svc_name, 0) + 1
                    
                    if _service_liveness_fails[svc_name] >= 3:
                        logger.error(f"Liveness Probe failed 3 times for {svc_name}. Emitting kill signal.")
                        # 通知控制平面(Sentinel) 介入强杀与驱逐
                        if r is not None:
                            try:
                                event = {
                                    "switch": svc_name,
                                    "state": "RESTART",
                                    "reason": "liveness_failed_3_times"
                                }
                                await r.publish("switch:events", json.dumps(event))
                            except Exception: pass
                        _service_liveness_fails[svc_name] = 0 # 重置计数，避免反复狂杀

            if r is not None: await r.aclose()
            await asyncio.sleep(10)

# -------------------- Lifespan --------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    # 启动后台 Bit-Rot 巡检与 SRE 探针
    br_task = asyncio.create_task(bitrot_worker())
    hp_task = asyncio.create_task(health_probe_worker())
    yield
    br_task.cancel()
    hp_task.cancel()
    _lru_cache.clear()


# -------------------- App --------------------
app = FastAPI(
    title="ZEN70 API Gateway",
    version="1.58.0",
    lifespan=lifespan,
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

from .ai_router import router as ai_router
app.include_router(ai_router)

# 注册 Prometheus ASGI 指标暴露端点
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)

# 注册低开销打点大闸
app.middleware("http")(metrics_middleware)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Trace-Id"]
)

# Phase 8 TraceID Middleware
app.add_middleware(TraceIDMiddleware)

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    """
    统一拦截 FastAPI 原生 HTTPException 构建标准化 ErrorResponse。
    法典 8.1 协议规定，将 TraceID 注入到 details 面板中。
    """
    trace_id = getattr(request.state, "trace_id", "unknown")
    logger.error(f"HTTP异常 拦截: {exc.status_code} - {exc.detail} - TraceID: {trace_id}")
    return JSONResponse(
            status_code=exc.status_code,
            content=ErrorResponse( # type: ignore
                code=f"HTTP-{exc.status_code}",
                message=str(exc.detail),
                recovery_hint="自动刷新前端页面或人工检查控制台网络面板",
                details={
                    "trace_id": trace_id
                }
            ).model_dump()
        )

@app.middleware("http")
async def global_readonly_lock(request: Request, call_next):
    """
    法典 3.2.4: UPS 熔断大闸。
    如果 Redis 能力矩阵探针汇报 UPS=LOW_BATTERY_SHUTDOWN，
    则全局拒绝所有 POST/PUT/DELETE/PATCH 写入请求（转入只读模式）。
    """
    if request.method in ("POST", "PUT", "DELETE", "PATCH"):
        # 我们优先读 _lru_cache 以避免每次写入都拉取 Redis
        matrix = _lru_cache.get("matrix")
        
        # 如果缓存为空，说明刚启动或者被清空，主动拉取一次兜底
        if matrix is None:
            # 由于不能直接在 middleware 轻易注入依赖，我们手写轻量获取
            try:
                r = await _get_redis()
                if r:
                    val = await r.get("zen70:topology:ups")
                    await r.aclose()
                    if val and val.strip().upper() == "LOW_BATTERY_SHUTDOWN":
                         return JSONResponse(
                             status_code=503,
                             content=ErrorResponse(
                                 code="ZEN-SYS-9999",
                                 message="市电中断且电池告警，系统已进入全局强制只读模式保护硬件",
                                 recovery_hint="等待市电恢复后，网关将自动解除锁定放行写入",
                                 details={
                                     "method": request.method, 
                                     "url": str(request.url),
                                     "trace_id": getattr(request.state, "trace_id", "unknown")
                                 },
                             ).model_dump()
                         )
            except Exception:
                pass
        else:
            ups_cap = matrix.get("ups")
            if ups_cap and ups_cap.status.lower() == "low-battery-shutdown":
                return JSONResponse(
                    status_code=503,
                    content=ErrorResponse(
                        code="ZEN-SYS-9999",
                        message="市电中断且电池告警，系统已进入全局强制只读模式保护硬件",
                        recovery_hint="等待市电恢复后，网关将自动解除锁定放行写入",
                        details={
                            "method": request.method, 
                            "url": str(request.url),
                            "trace_id": getattr(request.state, "trace_id", "unknown")
                        },
                    ).model_dump()
                )
            
    # 如果正常，或者只是 GET 请求，继续 Readiness 拦截
    # Readiness 拦截保护: 服务没有跑完模型加载等初始流程前，禁止流量切入 (这里用 path 前缀简单模拟路由隔离)
    path_str = str(request.url.path)
    for svc_name, is_ready in service_readiness.items():
        if not is_ready:
            # 判断此请求是否属于该瘫痪子服务 (这里简单的用名字包含路径来模拟微服务拆分)
            if svc_name in path_str:
                return JSONResponse(
                    status_code=503,
                    content=ErrorResponse(
                        code="ZEN-SVC-NOTREADY",
                        message=f"子服务 {svc_name} 尚未就绪 (Readiness Probe 失败), 流量已自动抛弃",
                        recovery_hint="请等待模型拉起完毕或节点自愈",
                        details={
                            "service": svc_name,
                            "trace_id": getattr(request.state, "trace_id", "unknown")
                        }
                    ).model_dump()
                )

    response = await call_next(request)
    return response


# 法典 7：禁止 API 无大小限制；有 Content-Length 时拒绝超限请求
MAX_REQUEST_BODY_BYTES = int(os.getenv("MAX_REQUEST_BODY_BYTES", "10485760"))  # 10MB

@app.middleware("http")
async def limit_request_body(request: Request, call_next):
    """请求体大小限制，超限返回 413。"""
    cl = request.headers.get("content-length")
    if cl and request.method in ("POST", "PUT", "PATCH"):
        try:
            size = int(cl)
            if size > MAX_REQUEST_BODY_BYTES:
                return JSONResponse(
                    status_code=413,
                    content=ErrorResponse(
                        code="ZEN-REQ-413",
                        message="Request entity too large",
                        recovery_hint=f"请求体不得超过 {MAX_REQUEST_BODY_BYTES // (1024*1024)} MB",
                        details={
                            "max_bytes": MAX_REQUEST_BODY_BYTES,
                            "trace_id": getattr(request.state, "trace_id", "unknown")
                        },
                    ).model_dump(),
                )
        except ValueError:
            pass
    return await call_next(request)


@app.middleware("http")
async def add_request_id(request: Request, call_next):
    """法典：所有响应携带 X-Request-ID。"""
    rid = request.headers.get("X-Request-ID") or str(uuid.uuid4())
    request.state.request_id = rid
    response = await call_next(request)
    response.headers["X-Request-ID"] = rid
    return response


# -------------------- 统一异常处理（法典 2.1.1 建议7）--------------------
@app.exception_handler(HTTPException)
async def http_handler(request: Request, exc: HTTPException):
    if isinstance(exc.detail, dict) and "code" in exc.detail:
        return JSONResponse(status_code=exc.status_code, content=exc.detail)
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(
            code=f"ZEN-HTTP-{exc.status_code}",
            message=str(exc.detail),
            recovery_hint="检查请求参数后重试",
            details={
                "request_id": getattr(request.state, "request_id", ""),
                "trace_id": getattr(request.state, "trace_id", "unknown")
            },
        ).model_dump(),
    )


@app.exception_handler(RequestValidationError)
async def validation_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=422,
        content=ErrorResponse(
            code="ZEN-VAL-422",
            message="请求参数校验失败",
            recovery_hint="请检查请求体格式与必填字段",
            details={
                "errors": exc.errors(),
                "trace_id": getattr(request.state, "trace_id", "unknown")
            },
        ).model_dump(),
    )


@app.exception_handler(Exception)
async def global_handler(request: Request, exc: Exception):
    rid = getattr(request.state, "request_id", "unknown")
    trace_id = getattr(request.state, "trace_id", "unknown")
    logger.exception(f"Unhandled Server Error: {exc}")
    return JSONResponse(
        status_code=500,
        content=ErrorResponse(
            code="ZEN-INT-5000",
            message="服务内部错误",
            recovery_hint="请稍后重试或联系管理员",
            details={"request_id": rid, "trace_id": trace_id},
        ).model_dump(),
    )


# -------------------- 路由 --------------------

@app.get("/api/v1/capabilities", response_model=Dict[str, CapabilityItem])
async def capabilities(
    request: Request,
    current_user: dict | None = Depends(get_current_user_optional)
):
    """
    法典 2.3.1：返回能力矩阵，供前端 v-for 动态渲染。
    法典 3.2.5：Redis 失联时返回 All-OFF 矩阵并带 X-ZEN70-Bus-Status: not-ready 告警。
    """
    matrix = await get_capabilities_matrix(request)
    bus_ready = getattr(request.state, "bus_ready", True)
    role = current_user.get("role", "family") if current_user else "guest"

    # Role-Based Rendering:
    if role != "admin":
        matrix = {k: v for k, v in matrix.items() if k not in ("容灾备份", "容器启停")}
    if role == "guest":
        matrix = {k: v for k, v in matrix.items() if k in ["ups", "network"]}

    if not bus_ready:
        return JSONResponse(
            content={k: v.model_dump() for k, v in matrix.items()},
            headers={"X-ZEN70-Bus-Status": "not-ready"},
        )
    return matrix


class PingRequest(BaseModel):
    """Ping 请求体：前端每 30s 调用，防 45s 超时 cancel。"""
    connection_id: str = Field(..., description="SSE 连接建立时下发的 ID")


@app.post("/api/v1/stream/ping")
async def stream_ping(body: PingRequest):
    """法典 2.1.1：前端每 30s 调此接口续期，否则 45s 后服务端 cancel SSE。"""
    _sse_last_ping[body.connection_id] = time.time()
    return {"ok": True}


@app.get("/api/v1/stream")
async def stream(request: Request):
    """
    法典 2.1.1：SSE 单向推送。前端每 30s 调 POST /api/v1/stream/ping 续期，
    后端 45s 未收到必须 cancel() 释放 FD，杜绝半开连接耗尽资源。
    """
    if redis is None:
        return JSONResponse(
            status_code=503,
            content=ErrorResponse(
                code="ZEN-SSE-5001",
                message="Redis 不可用，SSE 无法启动",
                recovery_hint="等待总线就绪后重试，禁止盲目轮询",
                details={"trace_id": getattr(request.state, "trace_id", "unknown")},
            ).model_dump(),
        )

    conn_id = str(uuid.uuid4())
    _sse_last_ping[conn_id] = time.time()

    async def event_gen():
        r, pub = None, None
        try:
            r = await _get_redis()
            if r is None:
                yield {"event": "error", "data": '{"code":"ZEN-SSE-5001"}'}
                return
            pub = r.pubsub()
            await pub.subscribe("hardware:events", "switch:events", "board:events")
            yield {"event": "connected", "data": f'{{"connection_id":"{conn_id}"}}'}
            while True:
                # 法典：45s 未收 Ping 必须 cancel
                if time.time() - _sse_last_ping.get(conn_id, 0) > SSE_PING_TIMEOUT:
                    break
                if getattr(request, "is_disconnected", None) and callable(request.is_disconnected):
                    if request.is_disconnected():
                        break
                try:
                    msg = await asyncio.wait_for(
                        pub.get_message(timeout=1.0, ignore_subscribe_messages=True),
                        timeout=2.0,
                    )
                    if msg and msg.get("type") == "message":
                        yield {"event": msg.get("channel", ""), "data": msg.get("data", "{}")}
                    else:
                        matrix = await get_capabilities_matrix(request)
                        yield {"event": "heartbeat", "data": str(matrix)}
                except asyncio.TimeoutError:
                    matrix = await get_capabilities_matrix(request)
                    yield {"event": "heartbeat", "data": str(matrix)}
                except asyncio.CancelledError:
                    break
        finally:
            _sse_last_ping.pop(conn_id, None)
            if pub:
                try:
                    await pub.unsubscribe("hardware:events", "switch:events", "board:events")
                except Exception:
                    pass
            if r:
                try:
                    await r.aclose()
                except Exception:
                    pass

    return EventSourceResponse(
        event_gen(),
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.get("/health")
async def health():
    """健康检查。"""
    r = await _get_redis()
    ok = False
    if r:
        try:
            await r.ping()
            ok = True
        except Exception:
            pass
        finally:
            try:
                await r.aclose()
            except Exception:
                pass
    return {"status": "healthy" if ok else "degraded", "redis": "ok" if ok else "error"}


@app.get("/api/v1/media/status")
async def media_status(request: Request):
    """示例路由：依赖 media_engine，PENDING 时 503。"""
    matrix = await get_capabilities_matrix(request)
    raise_503_if_pending("media_engine", matrix)
    return {"status": "online", "message": "媒体服务可用"}


class ShredRequest(BaseModel):
    """法典 3.3.2 - 数据可携带权与安全剿灭"""
    file_path: str = Field(..., description="宿主机或容器内待物理粉碎的绝对路径")


@app.delete("/api/v1/storage/shred")
async def secure_shredding(request: Request, body: ShredRequest):
    """
    法典 3.3.2: 安全覆写销毁 (Secure Shredding)。
    严禁使用 os.remove()。必须调用 Linux shred 指令
    执行 3 次随机覆写并以零结尾，确保数据不可物理恢复。
    """
    target = Path(body.file_path)
    
    if not target.exists() or not target.is_file():
        raise HTTPException(
            status_code=404,
            detail=ErrorResponse(
                code="ZEN-STOR-4040",
                message="目标文件不存在或不是标准文件",
                recovery_hint="请检查路径是否正确传递",
                details={"path": str(target)},
            ).model_dump()
        )

    # 异步执行，包裹 try-except，按法典抛出标准错误结构
    try:
        # 执行 shred -u -z -n 3
        # -u: 覆写后删除
        # -z: 最后用 0 填充以隐藏覆写痕迹
        # -n 3: 覆写 3 次
        process = await asyncio.create_subprocess_exec(
            "shred", "-u", "-z", "-n", "3", str(target),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        stdout, stderr = await process.communicate()
        
        if process.returncode != 0:
            logger_err = stderr.decode().strip()
            raise Exception(f"Shred command failed: {logger_err}")
            
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(
                code="ZEN-STOR-5003",
                message="底层安全粉碎执行失败",
                recovery_hint="检查容器是否具备执行 shred 的权限，或目标文件是否被占用",
                details={"error_msg": str(e), "path": str(target)},
            ).model_dump()
        )

    return {"status": "success", "message": f"文件 {target.name} 已彻底物理粉碎并擦除残留痕迹"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.main:app", host="0.0.0.0", port=8000, reload=True)

