#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
#
# ZEN70 拓扑监测探针 (Topology Sentinel)。
#
# 红线合规：滑动窗口防抖、三重交叉核验。
# 零硬编码：动态感知 UPS 接入（通过 upsc 或 USB 探测），不依赖 system.yaml。
from __future__ import annotations

import json
import logging
import os
import platform
import shutil
import subprocess
import time
from collections import deque
from typing import Deque, Dict, Optional, Tuple

import redis

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [SENTINEL] %(message)s",
)
logger = logging.getLogger(__name__)

REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
POLL_INTERVAL = 5
LOCK_TTL = 15  # 强制合规法典 2.1.4: 心跳中断超过 15 秒锁自动消散
WINDOW_SIZE = 3


# 挂载点配置：能力标签 -> (路径, 期望UUID可选, 最小剩余GB)。路径解耦：仅来自 .env（compiler 从 system.yaml 写入）
def _load_watch_targets() -> Dict[str, Tuple[str, Optional[str], int]]:
    raw = os.getenv("WATCH_TARGETS", "{}")
    try:
        data = json.loads(raw) if raw.strip() else {}
        out: Dict[str, Tuple[str, Optional[str], int]] = {}
        for k, v in data.items():
            if isinstance(v, (list, tuple)) and len(v) >= 1:
                path = str(v[0])
                uuid_val = str(v[1]) if len(v) > 1 and v[1] is not None else None
                min_gb = int(v[2]) if len(v) > 2 and v[2] is not None else 1
                out[k] = (path, uuid_val, min_gb)
        return out
    except (json.JSONDecodeError, ValueError, TypeError):
        return {}


WATCH_TARGETS: Dict[str, Tuple[str, Optional[str], int]] = _load_watch_targets()


def check_ups_status() -> Tuple[bool, Optional[str]]:
    """
    法典 3.2.4 & 零硬编码: 动态探测 UPS。
    尝试运行 `upsc ups`（假设 NUT 默认挂载为 ups）。
    返回: (UPS是否存在, 'ONLINE' 或 'LOW_BATTERY' 或 'OFFLINE' 等状态码)
    """
    if platform.system() != "Linux":
        # Windows 测试/降级环境默认不具备 NUT 原生通讯
        return False, None
    try:
        r = subprocess.run(
            ["upsc", "ups"],
            capture_output=True,
            text=True,
            timeout=3,
        )
        if r.returncode != 0:
            return False, None

        # 简单解析 ups.status 和 battery.charge
        out = r.stdout
        status_line = next((line for line in out.splitlines() if line.startswith("ups.status:")), "")
        charge_line = next((line for line in out.splitlines() if line.startswith("battery.charge:")), "")

        # 解析电量，若低于 20% 返回 LOW_BATTERY 触发熔断
        charge = 100
        if charge_line:
            try:
                charge = int(charge_line.split(":")[1].strip())
            except ValueError:
                pass

        if status_line:
            val = status_line.split(":")[1].strip().upper()
            if "OB" in val or "LB" in val or charge < 20:
                # OB=On Battery, LB=Low Battery
                return True, "LOW_BATTERY"
            return True, "ONLINE"

        return True, "ONLINE"
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return False, None


def get_redis_client() -> redis.Redis:
    password = os.getenv("REDIS_PASSWORD") or None
    user = os.getenv("REDIS_USER", "default")
    return redis.Redis(
        host=REDIS_HOST,
        port=REDIS_PORT,
        username=user if password else None,
        password=password,
        db=0,
        decode_responses=True,
    )


def get_uuid_via_lsblk(path: str) -> Optional[str]:
    """法典：UUID 核验必须调用 Linux 原生命令，禁止第三方库。"""
    if platform.system() != "Linux":
        return None
    try:
        result = subprocess.run(
            ["lsblk", "-o", "UUID,MOUNTPOINT", "-J"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            return None
        data = json.loads(result.stdout)
        path_resolved = str(Path(path).resolve())
        for dev in data.get("blockdevices", []):
            mp = dev.get("mountpoint")
            if mp and str(Path(mp).resolve()) == path_resolved:
                return dev.get("uuid") or None
        return None
    except (
        subprocess.TimeoutExpired,
        json.JSONDecodeError,
        FileNotFoundError,
        OSError,
    ):
        return None


def triple_verify(path: str, expected_uuid: Optional[str], min_gb: int) -> Tuple[bool, str]:
    """
    三重交叉核验（法典 3.2.2）：1.路径存在 2.UUID一致 3.最小剩余容量。
    """
    if not Path(path).exists():
        return False, "path_missing"
    if expected_uuid:
        actual = get_uuid_via_lsblk(path)
        if actual != expected_uuid:
            return False, f"uuid_mismatch(expected={expected_uuid},got={actual})"
    try:
        free = shutil.disk_usage(path).free
        min_bytes = min_gb * (1024**3)
        if free < min_bytes:
            return False, f"space_insufficient({free}<{min_bytes})"
    except OSError as e:
        return False, f"space_check_error:{e}"
    return True, "ok"


def check_hardware_status(
    r: redis.Redis,
    window_cache: Dict[str, Deque[bool]],
) -> None:
    """
    核心轮询：滑动窗口防抖（连续 3 次一致）后写入 Redis。
    探针仅负责写状态锁，严禁操作容器（法典熔断顺序由网关执行）。
    """
    for capability, (path, expected_uuid, min_gb) in WATCH_TARGETS.items():
        state_key = f"zen70:topology:{capability}"
        passed, reason = triple_verify(path, expected_uuid, min_gb)

        if capability not in window_cache:
            window_cache[capability] = deque(maxlen=WINDOW_SIZE)
        window_cache[capability].append(passed)

        if len(window_cache[capability]) < WINDOW_SIZE:
            continue

        vals = list(window_cache[capability])
        all_ok = all(vals)
        all_fail = not any(vals)

        if all_ok:
            r.set(state_key, "ONLINE", ex=LOCK_TTL)
            logger.debug(f"[{capability}] ONLINE path={path}")
        elif all_fail:
            r.set(state_key, "PENDING_MAINTENANCE", ex=LOCK_TTL)
            logger.warning(f"熔断 [{capability}] 路径丢失 连续{WINDOW_SIZE}次确认 " f"path={path} reason={reason}")

    # UPS 动态感知 (Plug & Play)
    ups_capability = "ups"
    state_key = f"zen70:topology:{ups_capability}"
    has_ups, ups_status = check_ups_status()

    if ups_capability not in window_cache:
        window_cache[ups_capability] = deque(maxlen=WINDOW_SIZE)

    # 如果不存在 UPS（拔除或没有安装），传入 True（代表不触发熔断），让缓存逐渐恢复为 True
    # 如果存在 UPS，且状态为 ONLINE，传入 True
    # 如果存在 UPS，且状态为 LOW_BATTERY，传入 False（触发熔断）
    is_safe = True
    if has_ups and ups_status == "LOW_BATTERY":
        is_safe = False

    window_cache[ups_capability].append(is_safe)

    if len(window_cache[ups_capability]) >= WINDOW_SIZE:
        vals = list(window_cache[ups_capability])
        all_safe = all(vals)
        all_danger = not any(vals)

        if all_safe:
            # 安全状态下，如果探测到 UPS，注册为 ONLINE；如果拔除了，完全不写 Redis 锁
            if has_ups:
                r.set(state_key, "ONLINE", ex=LOCK_TTL)
        elif all_danger:
            if has_ups:
                # 危险状态下，只有当 UPS 真实接入时才抛出报警锁
                r.set(state_key, "LOW_BATTERY_SHUTDOWN", ex=LOCK_TTL)
                logger.error("熔断 [UPS] 切断电源或电量见底，触发全域只读大闸！")


def main() -> None:
    logger.info("ZEN70 拓扑探针启动 (滑动窗口防抖+三重核验)")
    logger.info("Redis %s:%s 轮询周期 %ss 锁TTL %ss", REDIS_HOST, REDIS_PORT, POLL_INTERVAL, LOCK_TTL)

    r = get_redis_client()
    window_cache: Dict[str, Deque[bool]] = {}

    while True:
        try:
            r.ping()
            check_hardware_status(r, window_cache)
        except redis.ConnectionError:
            logger.error("Redis 失联，探针悲观静默等待（锁将TTL消散）")
        except Exception as e:
            logger.exception("探针异常: %s", e)
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
