/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description 离线存储服务
 * 读写 ZEN70Cache 中的能力矩阵，提供统一的数据源
 */
import { db, CAPABILITIES_ROW_ID } from "@/db";
import type { Capabilities } from "@/types/capability";

async function safe<T>(fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn();
  } catch (_err) {
    return fallback;
  }
}

/** 写入能力矩阵到 IndexedDB */
export async function saveCapabilities(data: Capabilities): Promise<void> {
  await safe(
    () =>
      db.capabilities.put({
        id: CAPABILITIES_ROW_ID,
        data,
        lastUpdated: Date.now(),
      }),
    undefined
  );
}

/** 从 IndexedDB 读取能力矩阵 */
export async function loadCapabilities(): Promise<Capabilities | null> {
  const row = await safe(() => db.capabilities.get(CAPABILITIES_ROW_ID), null);
  return row?.data ?? null;
}
