/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description WebAuthn (FIDO2) 前端鉴权服务打样
 * 
 * 符合法典 6.1.4: 采用 WebAuthn 协议，结合设备芯片实现生物特征识别
 */

/**
 * 校验浏览器是否支持 WebAuthn
 */
export const isWebAuthnSupported = (): boolean => {
  return (
    window.PublicKeyCredential !== undefined &&
    typeof window.PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable === "function"
  );
};

/**
 * 发起 WebAuthn 注册流程 (打样)
 * 实际调用需后端提供 publicKeyCredentialCreationOptions
 */
export const registerWebAuthn = async (creationOptions: PublicKeyCredentialCreationOptions) => {
  if (!isWebAuthnSupported()) {
    throw new Error("当前设备/浏览器不支持 WebAuthn");
  }
  
  try {
    const credential = await navigator.credentials.create({
      publicKey: creationOptions
    });
    return credential;
  } catch (error) {
    console.error("WebAuthn 注册失败", error);
    throw error;
  }
};

/**
 * 发起 WebAuthn 登录验证流程 (打样)
 * 实际调用需后端提供 publicKeyCredentialRequestOptions
 */
export const authenticateWebAuthn = async (requestOptions: PublicKeyCredentialRequestOptions) => {
  if (!isWebAuthnSupported()) {
    throw new Error("当前设备/浏览器不支持 WebAuthn");
  }

  try {
    const assertion = await navigator.credentials.get({
      publicKey: requestOptions
    });
    return assertion;
  } catch (error) {
    console.error("WebAuthn 验证失败", error);
    throw error;
  }
};
