/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description ZEN70 离线缓存数据库 (IndexedDB)
 * 使用 Dexie 封装，存储能力矩阵等数据，作为断网时的数据源
 */
import Dexie, { type Table } from "dexie";
import type { Capabilities } from "@/types/capability";

export interface CachedCapabilitiesRow {
  id: number;
  data: Capabilities;
  lastUpdated: number;
}

class ZEN70CacheDb extends Dexie {
  capabilities!: Table<CachedCapabilitiesRow, number>;

  constructor() {
    super("ZEN70Cache");
    this.version(1).stores({ capabilities: "id" });
  }
}

export const db = new ZEN70CacheDb();
export const CAPABILITIES_ROW_ID = 1;
