/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 */
import { defineStore } from "pinia";
import { ref, computed } from "vue";
import { decodePayload } from "@/utils/jwt";

const TOKEN_KEY = "zen70-token";

export type Role = "admin" | "family" | "child" | "elder" | "user";

export const useAuthStore = defineStore("auth", () => {
  const token = ref<string | null>(localStorage.getItem(TOKEN_KEY));
  
  const tokenPayload = computed(() => {
    return token.value ? decodePayload(token.value) : null;
  });

  const role = computed<Role>(() => {
    const t = token.value;
    if (!t) return "user";
    const p = decodePayload(t);
    const r = (p?.role ?? "user").toLowerCase();
    if (r === "admin" || r === "geek") return "admin";
    if (r === "长辈" || r === "elder" || r === "family_elder") return "elder";
    if (r === "family") return "family";
    if (r === "儿童" || r === "child" || r === "family_child") return "child";
    return (r as Role) || "user";
  });

  const aiRoutePreference = computed<string>(() => {
    return (tokenPayload.value as any)?.ai_route_preference || "auto";
  });

  const isAdmin = computed(() => role.value === "admin");
  const isFamily = computed(() => role.value === "family");
  const isChild = computed(() => role.value === "child");
  const isElder = computed(() => role.value === "elder");

  function setToken(t: string | null) {
    token.value = t;
    if (t) localStorage.setItem(TOKEN_KEY, t);
    else localStorage.removeItem(TOKEN_KEY);
  }

  async function updateAiPreference(preference: "local" | "cloud" | "auto") {
    const API_BASE = (import.meta.env.VITE_API_BASE_URL || "/api").replace(/\/$/, "");
    const res = await fetch(`${API_BASE}/v1/auth/me/ai-preference`, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${token.value}`
      },
      body: JSON.stringify({ preference })
    });
    if (!res.ok) {
      const data = await res.json();
      throw new Error(data.detail?.message || "Failed to update AI preference");
    }
    const data = await res.json();
    setToken(data.access_token);
  }

  return { token, tokenPayload, role, isAdmin, isFamily, isChild, isElder, aiRoutePreference, setToken, updateAiPreference };
});
