#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version: V2.0
# @compliance: strict-sre-ruleset
# WARNING: Auto-generated core module. Manual modifications may be overwritten by IaC compiler.
# 
# ZEN70 容灾备份引擎 (Disaster Recovery Engine)。
# 
# 红线合规：
# 1. 负载感知避让：探测 CPU/GPU 负载，若超载则静默退出推迟备份。
# 2. 不可变存储：调用 restic 支持 S3 Object Lock。
# 3. 完整性抽检：执行 restic check --read-data-subset。

import os
import sys
import yaml
import logging
import platform
import subprocess
import shutil
import pyzipper
from datetime import datetime
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [BACKUP-ENGINE] %(message)s",
)
logger = logging.getLogger(__name__)

# 法典 3.1.3: 分级标签 (critical, ephemeral, media)
# 强制从 system.yaml 读取需要备份的挂载点
SYSTEM_YAML_PATH = Path("/app/system.yaml") if os.path.exists("/app/system.yaml") else Path("../system.yaml")

def check_system_load() -> bool:
    """
    法典 3.4.1 负载感知避让。
    探测 CPU 与异构加速卡的实时负载，若超载返回 False，挂起任务。
    """
    if platform.system() != "Linux":
        logger.warning("非 Linux 环境，跳过严格负载阈值检测。")
        return True

    # 简单检测 1分钟平均负载
    try:
        with open("/proc/loadavg", "r") as f:
            load_1m = float(f.read().split()[0])
            cores = os.cpu_count() or 1
            if load_1m / cores > 0.75:
                logger.warning(f"CPU 负载过高 (1m load: {load_1m}, cores: {cores})，推迟备份任务。")
                return False
                
        # 简单探测 NVIDIA GPU ( nvidia-smi )
        r = subprocess.run(
            ["nvidia-smi", "--query-gpu=utilization.gpu", "--format=csv,noheader,nounits"],
            capture_output=True, text=True
        )
        if r.returncode == 0:
            utils = r.stdout.strip().splitlines()
            for u in utils:
                if int(u.strip()) > 80:
                    logger.warning(f"检测到高强度的 GPU 计算任务 (utilization: {u}%)，推迟备份任务。")
                    return False
                    
    except Exception as e:
        logger.error(f"负载探测异常 {e}，为保证安全，默认放行。")
    
    return True

def get_critical_volumes() -> list:
    """法典 3.1.3：从 system.yaml 提取 backup_tier: critical 的目录"""
    vols = []
    try:
        p = SYSTEM_YAML_PATH.resolve()
        if not p.exists():
            logger.error(f"无法找到 {p} 配置文件，备份终止。")
            return vols
            
        with open(p, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            
        svcs = data.get("services", {})
        for svc_name, svc_conf in svcs.items():
            for v in svc_conf.get("volumes", []):
                # 这里假设 IaC 配置以字典或带标签的形式标注了 backup_tier
                # 因为法典提到："在 system.yaml 中为挂载点引入 backup_tier 字段"
                # 为了防错兼容简单的 string mount point，提取左侧宿主机地址
                if isinstance(v, str):
                    host_mnt = v.split(":")[0]
                    # 假定 critical 目录路径规则，如果不符合预期可以跳过
                    if "data" in host_mnt or "config" in host_mnt or "db" in host_mnt:
                        vols.append(host_mnt)
                elif isinstance(v, dict):
                    if v.get("backup_tier") == "critical":
                        vols.append(v.get("source", ""))
    except Exception as e:
         logger.error(f"解析 yaml 出错：{e}")
         
    # 去重
    return list(set(vols))

def execute_restic_backup(targets: list):
    """
    执行 Restic 推流。法典 3.1.3要求 S3 Object Lock。
    要求底层已经 export 了 RESTIC_REPOSITORY 和 RESTIC_PASSWORD
    """
    for t in targets:
        if not t or not os.path.exists(t):
            logger.warning(f"目标目录 {t} 不存在或不合法，跳过备份。")
            continue
            
        logger.info(f"开始推流级备份：{t}")
        try:
            # 增量备份
            subprocess.run(["restic", "backup", str(t)], check=True)
        except subprocess.CalledProcessError as e:
            logger.error(f"目录 {t} 备份失败：{e}")
            raise

def verify_backup_integrity():
    """法典 3.4.2: 完整性抽检"""
    logger.info("执行备份数据块随机解密防静默腐败抽检 (5% subset)...")
    try:
        subprocess.run(["restic", "check", "--read-data-subset=5%"], check=True)
        logger.info("备份健康度校验通过！")
    except subprocess.CalledProcessError as e:
        logger.error("重大故障：备份数据块解密失败，勒索病毒或 Bit-Rot 腐败侦测！")
        raise

def create_ashbox_backup():
    """冷态全盘骨灰盒备份 (Digital Ashbox)"""
    password = os.getenv("ASHBOX_PASSWORD", "zen70_fallback_pass").encode()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_filename = f"ZEN70_Snapshot_{timestamp}.zip"
    
    # 1. 导出数据库
    try:
        logger.info("Exporting PostgreSQL database...")
        subprocess.run(
            "docker exec zen70-postgres pg_dump -U zen70 zen70 > db_dump.sql",
            shell=True, check=True
        )
    except Exception as e:
        logger.error(f"Failed to dump database: {e}")
        return
        
    try:
        with pyzipper.AESZipFile(zip_filename, 'w', compression=pyzipper.ZIP_DEFLATED, encryption=pyzipper.WZ_AES) as zf:
            zf.setpassword(password)
            # 添加 .env 和 db_dump.sql
            if os.path.exists(".env"):
                zf.write(".env", ".env")
            if os.path.exists("db_dump.sql"):
                zf.write("db_dump.sql", "db_dump.sql")
                
            media_path = os.getenv("MEDIA_PATH")
            if not media_path:
                media_path = str(Path.cwd() / "media")
            if os.path.exists(media_path):
                logger.info("Zipping Media assets...")
                for root, dirs, files in os.walk(media_path):
                    for file in files:
                        full_path = os.path.join(root, file)
                        arcname = os.path.relpath(full_path, media_path)
                        zf.write(full_path, f"media/{arcname}")
                        
        logger.info(f"✅ 骨灰盒冷态备份生成成功: {zip_filename}，密码为 {password.decode()}")
    except Exception as e:
         logger.error(f"Failed to create Ashbox zip: {e}")
    finally:
         if os.path.exists("db_dump.sql"):
             os.remove("db_dump.sql")

def main():
    if "--ashbox" in sys.argv:
        create_ashbox_backup()
        sys.exit(0)

    if os.getenv("BACKUP_ENABLED", "true").lower() == "false":
        logger.info("Backup engine is disabled via system.yaml configuration. Exiting silently.")
        sys.exit(0)

    if not os.getenv("RESTIC_REPOSITORY"):
        logger.error("缺少 RESTIC_REPOSITORY 环境变量，灾备引擎无法启动。")
        sys.exit(1)
        
    if not check_system_load():
        logger.info("Skipped due to high load")
        sys.exit(0) # 负载高静默退出交由下一个 cron，遵循法典 3.4.1
        
    targets = get_critical_volumes()
    if not targets:
        logger.warning("未抓取到属于 [critical] 级别的挂载卷，退出备份。")
        sys.exit(0)
        
    try:
        execute_restic_backup(targets)
        verify_backup_integrity()
    except Exception:
        sys.exit(1)

if __name__ == "__main__":
    main()
