#!/usr/bin/env python3
# AI-generated: ZEN70 Day-0 bootstrap — Docker SDK, 预检扩展, 挂载点预建, 拉取完整性校验
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
"""
ZEN70 初始化点火脚本：系统初始化的唯一入口。

- 跨平台（Windows / Linux / Mac）：所有路径基于 pathlib 动态解析项目根，无 C:\\、/path 等硬编码。
- IaC 移植：compiler 在项目根检查 .env，不存在则 secrets 自动生成并创建；无需手动指定绝对路径。
- 流程：环境预检 → 多源拉取+校验 → 挂载点预建 → 编译（含自动密文闭环）→ compose up（隧道优先）。
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import yaml

# Docker SDK：用于 daemon 检查、版本检查与更精确的异常类型（文档 1.1 建议）
try:
    import docker
    from docker.errors import DockerException
except ImportError:
    docker = None  # type: ignore[assignment]
    DockerException = Exception  # type: ignore[misc, assignment]

# ---------------------------------------------------------------------------
# 常量（禁止硬编码 URL/路径于业务逻辑，此处为默认值）
# ---------------------------------------------------------------------------
MIN_DISK_GB = 20
"""预检要求：可用磁盘空间不低于此值（GB）。"""

MIN_DOCKER_VERSION = (20, 10)
"""预检要求：Docker API 版本不低于此（major, minor）。"""

DEFAULT_PORTS = [80, 443, 5173, 8000]
"""预检端口冲突检查的默认端口列表（可从 system.yaml 覆盖）。"""

DEFAULT_CONFIG_NAME = "system.yaml"
"""默认配置文件名。"""

CHECKSUM_SUFFIX = ".sha256"
"""拉取完整性校验：与 system.yaml 同目录的 system.yaml.sha256 可选。"""

# 多源拉取顺序：GitHub → Gitee → 本地缓存（占位 URL 可由环境变量或 system 覆盖）
GIT_SOURCES = [
    "https://github.com/zen70/zen70-config.git",
    "https://gitee.com/zen70/zen70-config.git",
]

REPO_DIR_NAME = ".zen70_repo"
"""拉取时使用的本地克隆目录名。"""

MOUNT_OWNER_UID = 1000
MOUNT_OWNER_GID = 1000
"""挂载点预建后 chown 目标（文档 7.1.3 防夺舍）。"""


def _root() -> Path:
    """项目根目录（scripts 的上级），跨平台 pathlib 动态解析，禁止硬编码绝对路径。"""
    return Path(__file__).resolve().parent.parent


def _scripts_dir() -> Path:
    """scripts 目录。"""
    return Path(__file__).resolve().parent


def setup_logging(verbose: bool = False) -> logging.Logger:
    """配置 stderr 日志，返回 bootstrap logger。"""
    log = logging.getLogger("bootstrap")
    log.setLevel(logging.DEBUG if verbose else logging.INFO)
    if not log.handlers:
        h = logging.StreamHandler(sys.stderr)
        h.setFormatter(logging.Formatter("[%(levelname)s] %(message)s"))
        log.addHandler(h)
    return log


logger: Optional[logging.Logger] = None


# ---------------------------------------------------------------------------
# 环境预检（Docker SDK + 版本 / 端口 / 内核 / 磁盘）
# ---------------------------------------------------------------------------


def _get_docker_client():  # type: () -> Optional[object]
    """使用 DOCKER_HOST 寻址（与 .cursorrules 一致），返回 Docker 客户端或 None。"""
    if docker is None:
        return None
    try:
        return docker.from_env(timeout=15)
    except Exception:
        return None


def check_docker() -> tuple[bool, str]:
    """
    使用 Docker Python SDK 检查 daemon 是否运行且可用（更精确捕获 DockerException）。

    Returns:
        (成功, 失败时错误信息)。
    """
    if docker is None:
        return False, "未安装 docker 包，请 pip install -r scripts/requirements.txt"
    try:
        client = docker.from_env(timeout=15)
        client.ping()
        return True, ""
    except DockerException as e:
        return False, f"Docker daemon 不可用: {e}"
    except Exception as e:
        return False, str(e)


def check_docker_version(min_version: tuple[int, int] = MIN_DOCKER_VERSION) -> tuple[bool, str]:
    """
    检查 Docker Engine 版本是否 >= min_version（如 20.10）。
    使用 Version 字段（如 20.10.17），而非 ApiVersion（如 1.41，语义不同）。
    """
    if docker is None:
        return False, "未安装 docker 包，无法检查版本"
    try:
        client = docker.from_env(timeout=10)
        # 优先使用 Engine 版本（20.10.x），而非 API 版本（1.41）
        ver_str = client.version().get("Version") or client.version().get("ApiVersion") or "0.0"
        # 解析 "20.10.17" 或 "1.41"
        m = re.match(r"(\d+)\.(\d+)", ver_str)
        if not m:
            return False, f"无法解析 Docker 版本: {ver_str}"
        major, minor = int(m.group(1)), int(m.group(2))
        if (major, minor) >= min_version:
            return True, f"Docker 版本 {ver_str} >= {min_version[0]}.{min_version[1]}"
        return False, f"Docker 版本 {ver_str} 过低，需要 >= {min_version[0]}.{min_version[1]}"
    except DockerException as e:
        return False, f"获取 Docker 版本失败: {e}"
    except Exception as e:
        return False, str(e)


def _get_port_list_output() -> Optional[str]:
    """跨平台获取监听端口列表：Linux ss，Windows netstat。"""
    if platform.system() == "Windows":
        try:
            r = subprocess.run(
                ["netstat", "-ano"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            return r.stdout if r.returncode == 0 else None
        except Exception:
            return None
    try:
        r = subprocess.run(
            ["ss", "-tlnp"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return r.stdout if r.returncode == 0 else None
    except Exception:
        return None


def check_ports(ports: list[int]) -> tuple[bool, str]:
    """
    检查指定端口是否已被占用。

    Returns:
        (全部未被占用为 True, 错误或说明信息)。
    """
    out = _get_port_list_output()
    if not out:
        return True, "无法获取端口列表（ss/netstat 不可用），跳过端口检查"
    occupied: list[int] = []
    for port in ports:
        pattern = re.compile(rf":{port}\b")
        for line in out.splitlines():
            if pattern.search(line) and ("LISTEN " in line or "LISTENING" in line):
                occupied.append(port)
                break
    if not occupied:
        return True, f"端口 {ports} 无冲突"
    return False, f"端口已被占用: {occupied}，请使用 ss -tlnp (Linux) 或 netstat -ano (Windows) 排查"


def check_kernel_params() -> tuple[bool, str]:
    """
    检查内核参数（仅 Linux）：net.ipv4.ip_forward、net.core.rmem_max。
    Windows 直接返回通过。
    """
    if platform.system() != "Linux":
        return True, "非 Linux，跳过内核参数检查"
    checks: list[tuple[str, str, int]] = [
        ("/proc/sys/net/ipv4/ip_forward", "net.ipv4.ip_forward", 1),
        ("/proc/sys/net/core/rmem_max", "net.core.rmem_max", 212992),
    ]
    for path, name, min_val in checks:
        try:
            p = Path(path)
            if not p.exists():
                continue
            val = int(p.read_text().strip())
            if val < min_val:
                return False, f"{name}={val}，建议 >= {min_val}（可 sysctl 或忽略）"
        except Exception as e:
            if logger:
                logger.debug("读取 %s 失败: %s", path, e)
    return True, "内核参数检查通过或跳过"


def check_disk(path: Path, min_gb: int = MIN_DISK_GB) -> tuple[bool, str]:
    """
    检查指定路径所在磁盘可用空间是否 >= min_gb（GB）。
    跨平台：使用 shutil.disk_usage。

    Returns:
        (通过, 失败时错误信息)。
    """
    try:
        path = path.resolve()
        if not path.exists():
            path = path.parent
        total, _used, free = shutil.disk_usage(path)
        free_gb = free / (1024**3)
        if free_gb >= min_gb:
            return True, ""
        return False, f"可用磁盘空间不足：{free_gb:.1f} GB < {min_gb} GB（路径: {path}）"
    except Exception as e:
        return False, f"无法检查磁盘空间: {e}"


def _ports_from_config(config_path: Path) -> list[int]:
    """从 system.yaml 解析需检查的宿主机端口（services.*.ports 中 host 部分）。"""
    if not config_path.exists():
        return DEFAULT_PORTS
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        services = data.get("services") or {}
        ports: list[int] = []
        for _name, svc in services.items():
            if not isinstance(svc, dict):
                continue
            for p in svc.get("ports") or []:
                if isinstance(p, str) and ":" in p:
                    host_part = p.split(":")[0]
                    if host_part.isdigit():
                        ports.append(int(host_part))
                elif isinstance(p, int):
                    ports.append(p)
        return list(dict.fromkeys(ports)) if ports else []  # 无暴露端口时跳过检查，避免误报
    except Exception:
        return DEFAULT_PORTS


NTP_DRIFT_THRESHOLD_SEC = 1.0
"""法典 2.4：NTP 时间漂移超过此值（秒）拒绝启动。"""

NTP_SERVERS = ("0.pool.ntp.org", "time.cloudflare.com")
"""NTP 预检使用的服务器，依次尝试。"""


def _run_ntp_precheck() -> None:
    """
    法典 2.4：NTP 同步预检。漂移 >1s 直接拒绝启动。
    无 ntplib 或网络不可达时仅警告并继续（极寒离线环境自举）。
    """
    try:
        import ntplib
    except ImportError:
        if logger:
            logger.warning("NTP 预检跳过：未安装 ntplib，建议 pip install ntplib")
        print("[WARN] NTP 预检跳过（无 ntplib），极寒离线环境可忽略", file=sys.stderr)
        return
    client = ntplib.NTPClient()
    for server in NTP_SERVERS:
        try:
            response = client.request(server, version=3, timeout=3)
            offset = response.offset
            if abs(offset) > NTP_DRIFT_THRESHOLD_SEC:
                msg = f"NTP 时间漂移过大: {offset:.2f}s > {NTP_DRIFT_THRESHOLD_SEC}s（服务器 {server}）"
                if logger:
                    logger.error("%s", msg)
                print(f"[预检失败] {msg}", file=sys.stderr)
                sys.exit(1)
            if logger:
                logger.info("NTP 预检通过: %s offset=%.3fs", server, offset)
            return
        except (ntplib.NTPException, OSError, Exception) as e:
            if logger:
                logger.debug("NTP %s 不可达: %s", server, e)
            continue
    if logger:
        logger.warning("NTP 预检跳过：所有 NTP 服务器不可达（可能离线环境）")
    print("[WARN] NTP 预检跳过（网络不可达），极寒离线环境可忽略", file=sys.stderr)


def run_precheck(
    root: Path,
    min_disk_gb: int = MIN_DISK_GB,
    config_path: Optional[Path] = None,
) -> None:
    """
    执行环境预检：Docker（SDK ping + 版本）、端口冲突、内核参数、磁盘。
    不通过时打印错误并 sys.exit(1)。
    """
    ok, err = check_docker()
    if not ok:
        if logger:
            logger.error("Docker 预检失败: %s", err)
        print(f"[预检失败] Docker: {err}", file=sys.stderr)
        sys.exit(1)
    if logger:
        logger.info("Docker 预检通过")

    ok, msg = check_docker_version()
    if not ok:
        if logger:
            logger.warning("Docker 版本检查未通过: %s", msg)
        print(f"[预检失败] Docker 版本: {msg}", file=sys.stderr)
        sys.exit(1)
    if logger:
        logger.info("%s", msg)

    ports = _ports_from_config(config_path or root / DEFAULT_CONFIG_NAME)
    ok, err = check_ports(ports)
    if not ok:
        if logger:
            logger.error("端口预检失败: %s", err)
        print(f"[预检失败] 端口: {err}", file=sys.stderr)
        sys.exit(1)
    if logger:
        logger.info("%s", err)

    ok, msg = check_kernel_params()
    if not ok:
        if logger:
            logger.warning("内核参数: %s", msg)
        print(f"[预检失败] 内核: {msg}", file=sys.stderr)
        sys.exit(1)
    if logger:
        logger.debug("%s", msg)

    ok, err = check_disk(root, min_disk_gb)
    if not ok:
        if logger:
            logger.error("磁盘预检失败: %s", err)
        print(f"[预检失败] 磁盘: {err}", file=sys.stderr)
        sys.exit(1)
    if logger:
        logger.info("磁盘预检通过（>= %s GB）", min_disk_gb)

    # 【强制 NTP 同步预检】（法典 2.4）：漂移 >1s 拒绝启动；无 ntplib 或不可达时警告并继续（极寒离线）
    _run_ntp_precheck()

    # 【强制关闭 Swap】（法典 3.6）：仅 Linux，需 root
    if platform.system() == "Linux":
        try:
            r = subprocess.run(
                ["swapoff", "-a"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if r.returncode == 0:
                if logger:
                    logger.info("Swap 已关闭 (swapoff -a)")
            else:
                if logger:
                    logger.warning("swapoff -a 失败（可能需 root）: %s", (r.stderr or r.stdout or "").strip())
                print("[WARN] swapoff -a 未成功，建议以 root 执行点火", file=sys.stderr)
        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            if logger:
                logger.warning("swapoff 异常: %s", e)
            print("[WARN] 无法执行 swapoff，跳过", file=sys.stderr)


# ---------------------------------------------------------------------------
# 拉取完整性校验（文档 7.1.4）
# ---------------------------------------------------------------------------


def compute_file_sha256(path: Path) -> str:
    """计算文件 SHA256（十六进制）。"""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_pulled_config_checksum(
    config_path: Path,
    repo_path: Path,
    candidate_path: Path,
) -> tuple[bool, str]:
    """
    对拉取后的配置文件做完整性校验。
    若仓库中存在 system.yaml.sha256 或 config/system.yaml.sha256，则校验一致；
    否则仅计算并记录 SHA256，返回 True。

    Returns:
        (校验通过, 说明信息)。
    """
    if not config_path.exists():
        return False, "配置文件不存在"
    actual = compute_file_sha256(config_path)
    if logger:
        logger.info("配置文件 SHA256: %s", actual)
    # 可选：与同源 sha256 文件比对
    for sha_path in (
        candidate_path.parent / (candidate_path.name + CHECKSUM_SUFFIX),
        repo_path / (DEFAULT_CONFIG_NAME + CHECKSUM_SUFFIX),
        repo_path / "config" / (DEFAULT_CONFIG_NAME + CHECKSUM_SUFFIX),
    ):
        if sha_path.exists():
            try:
                expected = sha_path.read_text(encoding="utf-8").strip().split()[0]
                if len(expected) == 64 and all(c in "0123456789abcdef" for c in expected.lower()):
                    if actual.lower() == expected.lower():
                        return True, "校验和一致"
                    return False, f"校验和不一致: 期望 {expected[:16]}..., 实际 {actual[:16]}..."
            except Exception as e:
                if logger:
                    logger.warning("读取校验和文件失败 %s: %s", sha_path, e)
    return True, "无校验和文件，已记录 SHA256"


# ---------------------------------------------------------------------------
# 多源容灾拉取（try GitHub → Gitee → 本地缓存）+ 完整性校验
# ---------------------------------------------------------------------------


def pull_latest_config(root: Path, config_path: Path, offline: bool = False) -> bool:
    """
    多源拉取最新配置到项目根，保证 config_path 存在。

    顺序：GitHub → Gitee → 本地缓存（已有 system.yaml 或 repo 缓存）。
    拉取成功后会将仓库中的 system.yaml（或 config/system.yaml）复制到 config_path。
    具备 try/except 与日志；全部失败时若 config_path 已存在则视为使用本地缓存成功。

    Args:
        root: 项目根目录。
        config_path: 期望的 system.yaml 路径（如 root / "system.yaml"）。
        offline: 为 True 时不执行网络拉取，仅检查 config_path 或本地缓存是否存在。

    Returns:
        最终存在可用配置为 True，否则 False。
    """
    if config_path.exists():
        if logger:
            logger.info("已存在配置: %s，跳过拉取", config_path)
        return True

    if offline:
        if logger:
            logger.warning("离线模式且未找到 %s", config_path)
        return False

    repo_path = root / REPO_DIR_NAME
    sources = GIT_SOURCES

    for source in sources:
        try:
            if logger:
                logger.info("尝试拉取配置: %s", source)
            if repo_path.exists():
                r = subprocess.run(
                    ["git", "-C", str(repo_path), "pull", "--depth", "1", "origin", "main"],
                    capture_output=True,
                    text=True,
                    timeout=60,
                    cwd=str(root),
                )
                if r.returncode != 0:
                    if logger:
                        logger.warning("git pull 失败: %s", r.stderr or r.stdout)
                    continue
            else:
                r = subprocess.run(
                    [
                        "git", "clone", "--depth", "1",
                        "--single-branch", "--branch", "main",
                        source, str(repo_path),
                    ],
                    capture_output=True,
                    text=True,
                    timeout=120,
                    cwd=str(root),
                )
                if r.returncode != 0:
                    if logger:
                        logger.warning("git clone 失败: %s", r.stderr or r.stdout)
                    continue

            # 复制 system.yaml：仓库根 或 config/system.yaml
            for candidate in (repo_path / DEFAULT_CONFIG_NAME, repo_path / "config" / DEFAULT_CONFIG_NAME):
                if candidate.exists():
                    config_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(candidate, config_path)
                    ok_verify, msg_verify = verify_pulled_config_checksum(config_path, repo_path, candidate)
                    if not ok_verify:
                        if logger:
                            logger.error("拉取完整性校验失败: %s", msg_verify)
                        print(f"[ERROR] 拉取校验失败: {msg_verify}", file=sys.stderr)
                        continue
                    if logger:
                        logger.info("拉取成功并校验通过，已写入: %s", config_path)
                    return True

            if logger:
                logger.warning("仓库中未找到 %s，尝试下一源", DEFAULT_CONFIG_NAME)
        except subprocess.TimeoutExpired:
            if logger:
                logger.warning("拉取超时: %s", source)
        except Exception as e:
            if logger:
                logger.warning("拉取异常 %s: %s", source, e, exc_info=True)

    # 本地缓存：若之前拉取过，repo 内可能有
    for candidate in (repo_path / DEFAULT_CONFIG_NAME, repo_path / "config" / DEFAULT_CONFIG_NAME):
        if candidate.exists():
            config_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate, config_path)
            verify_pulled_config_checksum(config_path, repo_path, candidate)  # 仅记录，不阻断
            if logger:
                logger.info("使用本地缓存配置: %s", config_path)
            return True

    if logger:
        logger.error("所有源拉取失败且无本地缓存")
    return False


# ---------------------------------------------------------------------------
# 挂载点预建与权限（文档 7.1.3：防夺舍）
# ---------------------------------------------------------------------------


def ensure_mount_points(config_path: Path) -> None:
    """
    解析 system.yaml，在宿主机预建所有挂载卷目录并执行 chown 1000:1000（仅 Linux）。
    仅处理绝对路径（如 /mnt/media、/tmp/zen70-cache），忽略命名卷（如 postgres_data）。
    """
    if not config_path.exists():
        return
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        paths_to_ensure: list[Path] = []
        cap_storage = (data.get("capabilities") or {}).get("storage") or {}
        if isinstance(cap_storage, dict) and cap_storage.get("media_path"):
            p = Path(cap_storage["media_path"])
            if p.is_absolute():
                paths_to_ensure.append(p)
        # 仅预建典型宿主机绑定目录，避免创建容器内路径（如 /var/lib/postgresql/data）
        host_prefixes = ("/mnt", "/tmp", "/home")
        for _key, val in (data.get("storage") or {}).items():
            if isinstance(val, dict) and val.get("path"):
                p = Path(val["path"])
                if p.is_absolute() and any(str(p).startswith(prefix) for prefix in host_prefixes):
                    paths_to_ensure.append(p)
        seen: set[Path] = set()
        for p in paths_to_ensure:
            p = p.resolve()
            if p in seen:
                continue
            seen.add(p)
            try:
                p.mkdir(parents=True, exist_ok=True)
                if logger:
                    logger.info("挂载点已预建: %s", p)
                if platform.system() == "Linux" and os.geteuid() == 0:
                    try:
                        os.chown(p, MOUNT_OWNER_UID, MOUNT_OWNER_GID)
                    except OSError:
                        pass
                    for root_dir, dirs, files in os.walk(p, topdown=True):
                        for name in list(dirs) + list(files):
                            path = Path(root_dir) / name
                            try:
                                os.chown(path, MOUNT_OWNER_UID, MOUNT_OWNER_GID)
                            except OSError:
                                pass
                    if logger:
                        logger.info("已 chown -R %s:%s: %s", MOUNT_OWNER_UID, MOUNT_OWNER_GID, p)
                elif platform.system() == "Linux" and os.geteuid() != 0:
                    if logger:
                        logger.debug("非 root，跳过 chown %s", p)
            except OSError as e:
                if logger:
                    logger.warning("预建挂载点失败 %s: %s", p, e)
                print(f"[警告] 挂载点预建失败 {p}: {e}", file=sys.stderr)
    except Exception as e:
        if logger:
            logger.warning("解析配置以预建挂载点失败: %s", e)


# ---------------------------------------------------------------------------
# 执行编译器
# ---------------------------------------------------------------------------


def run_compiler(root: Path, config_path: Path, output_dir: Optional[Path] = None) -> None:
    """
    调用 scripts/compiler.py 生成 docker-compose.yml 和 .env。
    确保 -o 始终附带有效参数，避免 expected one argument 报错。
    """
    out = output_dir or root
    try:
        out_arg = "." if out.resolve() == root.resolve() else str(out.relative_to(root))
    except ValueError:
        out_arg = str(out)
    cmd = [
        sys.executable,
        str(_scripts_dir() / "compiler.py"),
        str(config_path),
        "-o",
        out_arg,
    ]
    if logger:
        logger.info("执行编译器: %s", " ".join(cmd))
    subprocess.run(cmd, cwd=str(root), check=True)
    if logger:
        logger.info("编译器执行完成")


# ---------------------------------------------------------------------------
# 供应链（法典 1.1）：私有镜像仓库 docker login
# ---------------------------------------------------------------------------


def _parse_env_for_registry(env_path: Path) -> tuple[str, str, str]:
    """从 .env 解析 REGISTRY_URL、REGISTRY_USER、REGISTRY_PASSWORD。"""
    url, user, pwd = "", "", ""
    if not env_path.exists():
        return url, user, pwd
    try:
        text = env_path.read_text(encoding="utf-8")
    except OSError:
        return url, user, pwd
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)=(.*)", line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        if not v or (v.startswith("${") and v.endswith("}")):
            continue
        if k == "REGISTRY_URL":
            url = v
        elif k == "REGISTRY_USER":
            user = v
        elif k == "REGISTRY_PASSWORD":
            pwd = v
    return url, user, pwd


def verify_pulled_image_digests(
    manifest_path: Path,
    root: Path,
    compose_file: Path,
) -> None:
    """
    若 images.manifest 存在，拉取镜像后校验 digest（法典 1.1 供应链）。
    格式：每行 image:tag 或 image:tag expected_sha256:xxx，注释以 # 开头。
    """
    if not manifest_path.exists():
        return
    try:
        text = manifest_path.read_text(encoding="utf-8")
    except OSError:
        if logger:
            logger.warning("无法读取 images.manifest: %s", manifest_path)
        return
    expected: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) >= 2 and parts[1].startswith("sha256:"):
            expected[parts[0]] = parts[1]
    if not expected:
        return
    env = os.environ.copy()
    env.setdefault("COMPOSE_PROJECT_NAME", "zen70")
    try:
        subprocess.run(
            ["docker", "compose", "-f", str(compose_file), "pull", "--quiet"],
            cwd=str(root),
            env=env,
            timeout=600,
            capture_output=True,
            check=False,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        if logger:
            logger.warning("compose pull 失败，跳过镜像校验: %s", e)
        return
    for image, exp_digest in expected.items():
        try:
            r = subprocess.run(
                ["docker", "image", "inspect", image, "--format", "{{json .RepoDigests}}"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if r.returncode != 0:
                if logger:
                    logger.warning("镜像 digest 校验跳过 %s: 未拉取或不存在", image)
                continue
            digests = json.loads(r.stdout or "[]")
            ok = any(exp_digest in d for d in digests if isinstance(d, str))
            if not ok:
                if logger:
                    logger.warning("镜像 digest 不匹配: %s 期望 %s 实际 %s", image, exp_digest, digests)
                print(f"[WARN] 镜像 {image} digest 与 manifest 不符", file=sys.stderr)
        except Exception as e:
            if logger:
                logger.debug("digest 校验异常 %s: %s", image, e)


def docker_login_registry_if_needed(env_path: Path) -> None:
    """
    若 .env 中 REGISTRY_URL 与 REGISTRY_USER 已配置且非空，执行 docker login。
    密码经 stdin 传入，避免出现在进程列表中。
    """
    url, user, pwd = _parse_env_for_registry(env_path)
    if not (url.strip() and user.strip()):
        if logger:
            logger.debug("未配置 REGISTRY_URL / REGISTRY_USER，跳过 docker login")
        return
    try:
        args = ["docker", "login", url.strip(), "-u", user.strip(), "--password-stdin"]
        r = subprocess.run(
            args,
            input=pwd,
            capture_output=True,
            text=True,
            timeout=15,
        )
        if r.returncode != 0:
            err = (r.stderr or r.stdout or "").strip()
            if logger:
                logger.warning("docker login %s 失败: %s", url, err)
            print(f"[WARN] 私有镜像仓库登录失败: {err}", file=sys.stderr)
        elif logger:
            logger.info("私有镜像仓库 %s 登录成功", url)
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        if logger:
            logger.warning("docker login 异常: %s", e)
        print(f"[WARN] 私有镜像仓库登录异常: {e}", file=sys.stderr)


# ---------------------------------------------------------------------------
# 启动顺序：先隧道（cloudflared），再其余（Docker SDK 预验 + 精确异常捕获）
# ---------------------------------------------------------------------------


def compose_up(root: Path, compose_file: Path, tunnel_service: str = "cloudflared") -> None:
    """
    使用 Docker SDK 预验证 daemon 后，通过 subprocess 执行 docker compose up -d --remove-orphans。
    异常时捕获 stderr 并抛出明确错误（文档 1.1 建议更精确捕获）。
    若 compose 中存在 tunnel_service，则先 up 该服务，再 up 全部（幂等）。
    """
    compose_file = compose_file.resolve()
    if not compose_file.exists():
        if logger:
            logger.error("compose 文件不存在: %s", compose_file)
        print(f"[ERROR] 未找到 {compose_file}", file=sys.stderr)
        sys.exit(1)

    if docker is not None:
        try:
            client = docker.from_env(timeout=10)
            client.ping()
        except DockerException as e:
            print(f"[ERROR] Docker daemon 不可用: {e}", file=sys.stderr)
            sys.exit(1)

    env = os.environ.copy()
    env.setdefault("COMPOSE_PROJECT_NAME", "zen70")

    def run_compose(services: Optional[list[str]] = None) -> None:
        args = ["docker", "compose", "-f", str(compose_file), "up", "-d", "--remove-orphans"]
        if services:
            args.extend(services)
        if logger:
            logger.info("执行: %s", " ".join(args))
        try:
            r = subprocess.run(
                args,
                cwd=str(root),
                env=env,
                timeout=300,
                capture_output=True,
                text=True,
            )
            if r.returncode != 0:
                err = (r.stderr or r.stdout or "").strip()
                print(f"[ERROR] docker compose 返回 {r.returncode}", file=sys.stderr)
                if err:
                    print(err, file=sys.stderr)
                sys.exit(1)
        except subprocess.TimeoutExpired:
            print("[ERROR] docker compose 执行超时 (300s)", file=sys.stderr)
            sys.exit(1)
        except FileNotFoundError:
            print("[ERROR] 未找到 docker 或 compose 插件，请确保已安装 Docker Engine 与 Compose V2", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[ERROR] docker compose 异常: {e}", file=sys.stderr)
            raise

    # 检查是否包含隧道服务（简单解析 YAML 中 services 下是否有 cloudflared）
    try:
        content = compose_file.read_text(encoding="utf-8")
        has_tunnel = f"{tunnel_service}:" in content or f"  {tunnel_service}:" in content
    except Exception:
        has_tunnel = False

    if has_tunnel:
        run_compose([tunnel_service])
    run_compose()  # 全部 up（幂等）


# ---------------------------------------------------------------------------
# 主流程（幂等）
# ---------------------------------------------------------------------------


def main() -> None:
    global logger
    parser = argparse.ArgumentParser(description="ZEN70 初始化点火脚本（幂等）")
    parser.add_argument(
        "--config",
        default=DEFAULT_CONFIG_NAME,
        help="system.yaml 路径（相对项目根或绝对），默认 system.yaml",
    )
    parser.add_argument(
        "-o", "--output-dir",
        default=None,
        help="编译器输出目录，默认与项目根一致",
    )
    parser.add_argument(
        "--skip-pull",
        action="store_true",
        help="跳过多源拉取，仅使用已有配置",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="离线模式：不拉取，仅当已有配置时继续",
    )
    parser.add_argument(
        "--min-disk-gb",
        type=int,
        default=MIN_DISK_GB,
        help=f"预检最小可用磁盘（GB），默认 {MIN_DISK_GB}",
    )
    parser.add_argument(
        "--no-up",
        action="store_true",
        help="仅预检+拉取+编译，不执行 docker-compose up",
    )
    parser.add_argument(
        "--skip-mounts",
        action="store_true",
        help="跳过挂载点预建与 chown（仍会执行其他预检与编译）",
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="详细日志",
    )
    args = parser.parse_args()

    logger = setup_logging(verbose=args.verbose)
    root = _root()
    # 路径均基于项目根；支持相对路径（如 system.yaml、config/system.yaml）
    config_path = root / args.config if not Path(args.config).is_absolute() else Path(args.config)
    output_dir = root / args.output_dir if args.output_dir else root

    # 1. 环境预检（含 Docker 版本、端口、内核、磁盘；config 存在时从 config 解析端口）
    run_precheck(root, min_disk_gb=args.min_disk_gb, config_path=config_path)

    # 2. 多源拉取（除非 --skip-pull）+ 拉取后完整性校验
    if not args.skip_pull:
        if not pull_latest_config(root, config_path, offline=args.offline):
            if not config_path.exists():
                logger.error("无可用配置且拉取失败，退出")
                print("[ERROR] 无可用配置（可尝试 --offline 并使用已有 system.yaml）", file=sys.stderr)
                sys.exit(1)
    else:
        if not config_path.exists():
            print(f"[ERROR] 未找到配置: {config_path}", file=sys.stderr)
            sys.exit(1)
        if logger:
            logger.info("已存在配置: %s", config_path)

    # 3. 挂载点预建与权限（文档 7.1.3）
    if not args.skip_mounts:
        ensure_mount_points(config_path)

    # 4. 执行编译
    run_compiler(root, config_path, output_dir)

    # 5. 启动顺序控制（Docker SDK 预验 + compose up -d --remove-orphans）
    if not args.no_up:
        env_path = output_dir / ".env"
        docker_login_registry_if_needed(env_path)
        compose_file = output_dir / "docker-compose.yml"
        manifest_path = config_path.parent / "images.manifest"
        verify_pulled_image_digests(manifest_path, root, compose_file)
        compose_up(root, compose_file)
        # 6. 自动化基座验真（平级导入，避免 ModuleNotFoundError）
        try:
            _scripts = str(_scripts_dir())
            if _scripts not in sys.path:
                sys.path.insert(0, _scripts)
            import verify
            if logger:
                logger.info("触发底层自动化验真探针...")
            verify.verify_infrastructure(exit_on_fail=True)
        except ImportError as e:
            print(f"[ERROR] 无法导入验证模块: {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[ERROR] 验真过程异常: {e}", file=sys.stderr)
            sys.exit(1)

    if logger:
        logger.info("bootstrap 完成（幂等）")


if __name__ == "__main__":
    main()
