#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
# AI-generated: 法典 7.1.2 自动化安全凭证注入，跨平台 IaC 移植
"""
配置编译器：将 system.yaml 渲染为 docker-compose.yml 和 .env。

- 路径：全部基于项目根（pathlib 动态解析），禁止硬编码 C:\\、/path 等绝对路径。
- 密文闭环：编译时检查项目根 .env，不存在则 secrets 模块生成强密码并自动创建。
- ENV_FILE：支持相对路径（相对项目根），如 ENV_FILE=secrets.env → 根目录/secrets.env。
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import sys
from datetime import datetime, timezone
from pathlib import Path

import jinja2
import yaml

# ---------------------------------------------------------------------------
# 敏感密钥清单（法典 7.1.2）：需生成或从外部注入，严禁硬编码默认密码
# ---------------------------------------------------------------------------
SECRET_KEYS = (
    "POSTGRES_PASSWORD",
    "JWT_SECRET_CURRENT",
    "JWT_SECRET_PREVIOUS",
    "REDIS_PASSWORD",
    "CLOUDFLARED_TUNNEL_TOKEN",
    "TUNNEL_TOKEN",
    "HEADSCALE_PRIVATE_KEY",
    "AI_BACKEND_URL",
)
"""必须解析的敏感键名；缺失时按需生成或留空。"""

# 缺失时自动生成（32 位高强随机）；其余仅保留已有值
GENERATE_IF_MISSING = ("POSTGRES_PASSWORD", "JWT_SECRET_CURRENT", "REDIS_PASSWORD")

# 特殊默认值映射
DEFAULT_VALUES = {
    "AI_BACKEND_URL": "http://ollama:11434"
}


def config_lint(path: Path) -> dict:
    """
    config-lint：校验 YAML 格式合法性。
    返回解析后的配置字典；格式非法时打印错误并 sys.exit(1)。
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        print(f"[config-lint] 无法读取文件: {path}", file=sys.stderr)
        sys.exit(1)
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        print(f"[config-lint] YAML 格式非法: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(data, dict):
        print("[config-lint] 根节点必须为字典", file=sys.stderr)
        sys.exit(1)
        
    version = data.get("version")
    if not version:
        print("[WARN] [config-lint] system.yaml 缺失 version 字段。建议补充以启用自动配置迁移。当前架构规范要求 V2.0+ (法典 7.1.5)。")
    elif str(version) < "2.0":
        print(f"[WARN] [config-lint] 检测到旧版本配置 ({version})。请注意，新版架构引擎如果涉及弃用的参数，请参阅 docs/adr/ 决定并手写迁移扩展！")

    return data


def prepare_services(config: dict) -> list[dict]:
    """
    逻辑聚合：将 services 预处理为模板可用的列表。
    每个元素为扁平的 dict，含 name、image、及预格式化的 YAML 块字符串。
    """
    services_raw = config.get("services") or {}
    result: list[dict] = []
    for name, svc in services_raw.items():
        if not isinstance(svc, dict):
            continue
        if svc.get("enabled") is False:
            continue
        if name == "cloudflared" and not (config.get("network") or {}).get("tunnel_enabled", True):
            continue
        # 构建服务块（纯字符串，模板仅做插入）
        image = svc.get("image", "unknown")
        reg = config.get("registry") or {}
        if reg.get("enabled") and reg.get("url") and not svc.get("build"):
            url = str(reg.get("url", "")).strip()
            if url and not image.startswith("${") and not image.startswith("http"):
                image = f"{url.rstrip('/')}/{image}"
        build_block = ""
        build_cfg = svc.get("build")
        if isinstance(build_cfg, dict):
            ctx = build_cfg.get("context", ".")
            df = build_cfg.get("dockerfile", "")
            if df:
                build_block = f"    build:\n      context: {ctx}\n      dockerfile: {df}\n"
        container_name = svc.get("container_name") or f"zen70-{name}"
        restart = "unless-stopped"

        # security 块（仅当 apply_baseline=True 时）
        security_block = ""
        sec = svc.get("security") or {}
        if sec.get("apply_baseline"):
            user = sec.get("user", "${PUID:-1000}:${PGID:-1000}")
            security_block = f"    user: '{user}'\n    read_only: true\n    cap_drop:\n      - ALL\n    cap_add:\n      - NET_BIND_SERVICE\n"

        # volumes
        vols = svc.get("volumes") or []
        volumes_block = ""
        if vols:
            volumes_block = "    volumes:\n" + "\n".join(f"      - {v}" for v in vols) + "\n"

        # environment（法典 1.2：postgres/cloudflared 预留挂载位）
        env = dict(svc.get("environment") or {})
        if name == "postgres":
            env.setdefault("POSTGRES_USER", "${POSTGRES_USER}")
            env.setdefault("POSTGRES_PASSWORD", "${POSTGRES_PASSWORD}")
            env.setdefault("POSTGRES_DB", "${POSTGRES_DB}")
        if name == "cloudflared":
            env.setdefault("TUNNEL_TOKEN", "${TUNNEL_TOKEN}")
        env_block = ""
        if env:
            lines = [f'      - {k}={v}' for k, v in env.items()]
            env_block = "    environment:\n" + "\n".join(lines) + "\n"

        # ports
        ports = svc.get("ports") or []
        ports_block = ""
        if ports:
            ports_block = "    ports:\n" + "\n".join(f"      - {p}" for p in ports) + "\n"

        # command（system.yaml 为唯一来源，不在此处兜底）
        cmd = svc.get("command")
        command_block = ""
        if cmd:
            if isinstance(cmd, list):
                cmd_str = ", ".join(repr(c) for c in cmd)
                command_block = f"    command: [{cmd_str}]\n"
            else:
                command_block = f'    command: "{cmd}"\n'

        # depends_on (法典 Phase 7: 支持 Init Containers 声明式前置依赖)
        deps = svc.get("depends_on")
        deps_block = ""
        if isinstance(deps, list) and len(deps) > 0:
            deps_block = "    depends_on:\n" + "\n".join(f"      - {d}" for d in deps) + "\n"
        elif isinstance(deps, dict) and len(deps) > 0:
            deps_block = "    depends_on:\n"
            for dep_name, dep_config in deps.items():
                deps_block += f"      {dep_name}:\n"
                if isinstance(dep_config, dict):
                    for k, v in dep_config.items():
                        deps_block += f"        {k}: {v}\n"
                elif isinstance(dep_config, str):
                    # 兼容类似 postgres: condition: service_healthy 被简写的情况
                    deps_block += f"        condition: {dep_config}\n"

        # 网络归属（法典 1.2）：postgres/redis 仅 backend_net，严禁 frontend_net
        nets = svc.get("networks")
        if not nets:
            if name == "cloudflared":
                nets = ["frontend_net", "backend_net"]
            else:
                nets = ["backend_net"]
        if name in ("postgres", "redis"):
            nets = [n for n in nets if n == "backend_net"] or ["backend_net"]
        networks_block = "    networks:\n" + "\n".join(f"      - {n}" for n in nets) + "\n"

        # 法典 3.3：核心容器 ulimits nofile=65536；探针/网关/Redis oom_score_adj -999
        ulimits_block = ""
        oom_score_adj_block = ""
        if name in ("gateway", "redis"):
            ulimits_block = "    ulimits:\n      nofile:\n        soft: 65536\n        hard: 65536\n"
            oom_score_adj_block = "    oom_score_adj: -999\n"

        # 法典 3.4：安全容器规范必须配置 healthcheck；gateway/redis 默认注入
        healthcheck_block = ""
        hc = svc.get("healthcheck")
        if name == "gateway":
            healthcheck_block = (
                "    healthcheck:\n"
                "      test: [\"CMD-SHELL\", \"python -c \\\"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5)\\\" || exit 1\"]\n"
                "      interval: 30s\n      timeout: 10s\n      retries: 3\n"
            )
        elif name == "redis":
            healthcheck_block = (
                "    healthcheck:\n"
                "      test: [\"CMD\", \"redis-cli\", \"ping\"]\n"
                "      interval: 30s\n      timeout: 10s\n      retries: 3\n"
            )
        elif isinstance(hc, dict) and hc.get("test"):
            th = hc.get("interval", "30s")
            to = hc.get("timeout", "10s")
            ret = hc.get("retries", 3)
            t = hc["test"]
            test_str = "[" + ", ".join(repr(x) for x in (t if isinstance(t, list) else [t])) + "]"
            healthcheck_block = f"    healthcheck:\n      test: {test_str}\n      interval: {th}\n      timeout: {to}\n      retries: {ret}\n"

        # deploy (Resources Limits / Reservations)
        deploy_block = ""
        deploy_cfg = svc.get("deploy")
        if isinstance(deploy_cfg, dict):
            deploy_block = yaml.dump({"deploy": deploy_cfg}, default_flow_style=False, sort_keys=False)
            # Indent deploy block by 4 spaces
            deploy_block = "".join(f"    {line}\n" for line in deploy_block.splitlines() if line.strip())

        result.append({
            "name": name,
            "image": image,
            "build_block": build_block,
            "container_name": container_name,
            "restart": restart,
            "security_block": security_block,
            "ulimits_block": ulimits_block,
            "oom_score_adj_block": oom_score_adj_block,
            "healthcheck_block": healthcheck_block,
            "volumes_block": volumes_block,
            "environment_block": env_block,
            "command_block": command_block,
            "ports_block": ports_block,
            "depends_on_block": deps_block,
            "networks_block": networks_block,
            "deploy_block": deploy_block,
        })
    return result


def _extract_networks(config: dict) -> list[dict]:
    """
    从根节点 networks 或 network.planes 提取网络定义（法典 1.2）。
    返回 [{"name": str, "driver": str, "internal": bool}, ...]
    """
    nets = config.get("networks") or (config.get("network") or {}).get("planes") or {}
    if nets:
        return [
            {
                "name": name,
                "driver": (v.get("driver") or "bridge") if isinstance(v, dict) else "bridge",
                "internal": bool(v.get("internal")) if isinstance(v, dict) else False,
            }
            for name, v in nets.items()
        ]
    seen: set[str] = set()
    for _n, svc in (config.get("services") or {}).items():
        if isinstance(svc, dict):
            for n in svc.get("networks") or []:
                seen.add(str(n).strip())
    default_nets = sorted(seen) or ["frontend_net", "backend_net"]
    return [{"name": n, "driver": "bridge", "internal": n == "backend_net"} for n in default_nets]


def _extract_named_volumes(config: dict) -> list[str]:
    """从 services.*.volumes 提取命名卷名（格式 name:path，非 / 开头为命名卷）。"""
    seen: set[str] = set()
    for _name, svc in (config.get("services") or {}).items():
        if not isinstance(svc, dict):
            continue
        for v in svc.get("volumes") or []:
            s = str(v).strip()
            if ":" in s:
                name = s.split(":")[0].strip()
                if name and not name.startswith("/") and not name.startswith("."):
                    seen.add(name)
    return sorted(seen)


def _resolve_env_default(val: str | None, default: str) -> str:
    """配置为占位符（${VAR}）时返回 default，否则返回原值。"""
    if not val or (isinstance(val, str) and val.startswith("${") and val.endswith("}")):
        return default
    return str(val)


def _parse_env_file(path: Path) -> dict[str, str]:
    """解析 .env 格式文件，返回 KEY -> value 字典。忽略空行、注释、占位符。"""
    result: dict[str, str] = {}
    if not path.exists():
        return result
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return result
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)=(.*)", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        # 去除首尾引号
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        if val and not (val.startswith("${") and val.endswith("}")):  # 非占位符
            result[key] = val
    return result


def _load_existing_secrets(project_root: Path) -> dict[str, str]:
    """
    从已有 .env 和 ENV_FILE 加载凭证（全基于项目根，跨平台）。
    优先级：project_root/.env > project_root/ENV_FILE（相对路径）> os.environ。
    ENV_FILE 支持相对路径，如 secrets.env → project_root/secrets.env。
    """
    merged: dict[str, str] = {}
    sources: list[Path] = []
    env_path = project_root / ".env"
    if env_path.exists():
        sources.append(env_path)
    env_file = os.environ.get("ENV_FILE")
    if env_file:
        p = Path(env_file)
        if not p.is_absolute():
            p = (project_root / p).resolve()  # 相对路径：基于项目根
        else:
            p = p.resolve()
        if p.exists() and p not in sources:
            sources.append(p)
    for path in sources:
        for k, v in _parse_env_file(path).items():
            if k in SECRET_KEYS and v and k not in merged:
                merged[k] = v
    for k in SECRET_KEYS:
        if k not in merged and k in os.environ and os.environ[k]:
            merged[k] = os.environ[k]
    return merged


TUNNEL_TOKEN_PLACEHOLDER = "your_cloudflare_token_here_replace_me"
"""TUNNEL_TOKEN 缺失时注入的占位符，严禁硬编码真实 token。"""


def generate_secrets(project_root: Path, base_env: dict) -> dict:
    """
    防腐凭证中心：幂等解析敏感凭证。
    - POSTGRES_PASSWORD：已有则保留，绝对不覆盖。
    - TUNNEL_TOKEN：.env 中缺失时自动注入占位符。
    返回合并后的 env 字典，供 .env.j2 渲染。
    """
    return _resolve_secrets_for_env(project_root, base_env)


def _resolve_secrets_for_env(project_root: Path, base_env: dict) -> dict:
    """
    幂等解析敏感凭证：已有值保留，缺失则生成（仅 GENERATE_IF_MISSING）。
    返回合并后的 env 字典，供 .env.j2 渲染。
    """
    existing = _load_existing_secrets(project_root)
    out = dict(base_env)
    out["postgres_password"] = (
        existing.get("POSTGRES_PASSWORD")
        or (secrets.token_urlsafe(32) if "POSTGRES_PASSWORD" in GENERATE_IF_MISSING else "")
    )
    out["jwt_secret_current"] = (
        existing.get("JWT_SECRET_CURRENT")
        or (secrets.token_urlsafe(32) if "JWT_SECRET_CURRENT" in GENERATE_IF_MISSING else "")
    )
    out["jwt_secret_previous"] = existing.get("JWT_SECRET_PREVIOUS", "")
    out["redis_password"] = (
        existing.get("REDIS_PASSWORD")
        or (secrets.token_urlsafe(32) if "REDIS_PASSWORD" in GENERATE_IF_MISSING else "")
    )
    # TUNNEL_TOKEN：缺失时注入占位符，已有值（含占位符）幂等保留
    tunnel_val = existing.get("TUNNEL_TOKEN") or existing.get("CLOUDFLARED_TUNNEL_TOKEN")
    if not tunnel_val or tunnel_val in ("your_cloudflare_token_here", TUNNEL_TOKEN_PLACEHOLDER):
        tunnel_val = TUNNEL_TOKEN_PLACEHOLDER
    out["tunnel_token"] = tunnel_val

    # AI_BACKEND_URL
    out["ai_backend_url"] = existing.get("AI_BACKEND_URL") or DEFAULT_VALUES.get("AI_BACKEND_URL", "http://ollama:11434")
    
    return out


def prepare_env(config: dict) -> dict:
    """
    逻辑聚合：提取 .env 所需变量。配置中的占位符对应默认值。
    敏感凭证（postgres_password、jwt_secret_*）由 _resolve_secrets_for_env 注入，此处仅占位。
    法典路径解耦：MEDIA_PATH、MOUNT_CONTAINER_MAP、WATCH_TARGETS、BITROT_SCAN_DIRS 仅来自 system.yaml。
    """
    network = config.get("network") or {}
    services = config.get("services") or {}
    pg_env = (services.get("postgres") or {}).get("environment") or {}
    cap_storage = (config.get("capabilities") or {}).get("storage") or {}
    sentinel_cfg = config.get("sentinel") or {}
    media_path = cap_storage.get("media_path") or ""
    mount_map = sentinel_cfg.get("mount_container_map") or {}
    watch_targets = sentinel_cfg.get("watch_targets") or {}
    bitrot_dirs = [media_path]
    if sentinel_cfg.get("models_path"):
        bitrot_dirs.append(sentinel_cfg["models_path"])
    elif isinstance(watch_targets.get("ai_vision"), (list, tuple)) and watch_targets["ai_vision"]:
        bitrot_dirs.append(watch_targets["ai_vision"][0])
        
    # 根据法典 1.1 的环境解耦要求，直接从 system.yaml 唯一真相源提取开关到容器的映射，零硬编码代码推理
    switch_map = sentinel_cfg.get("switch_container_map") or {}
    
    return {
        "postgres_user": _resolve_env_default(pg_env.get("POSTGRES_USER"), "zen70"),
        "postgres_db": _resolve_env_default(pg_env.get("POSTGRES_DB"), "zen70"),
        "postgres_password": "",  # 由 _resolve_secrets_for_env 注入
        "redis_host": "redis",
        "redis_port": 6379,
        "redis_password": "",  # 由 _resolve_secrets_for_env 注入
        "redis_user": "zen70_gateway",
        "jwt_secret_current": "",
        "jwt_secret_previous": "",
        "domain": network.get("domain", "home.zen70.local"),
        "tunnel_token": "",  # 由 _resolve_secrets_for_env 注入
        "ai_backend_url": "",  # 由 _resolve_secrets_for_env 注入
        "backup_enabled": "true" if (isinstance(config.get("backup"), dict) and config["backup"].get("enabled")) else "false",
        "media_path": media_path,
        "bitrot_scan_dirs": ",".join(str(p).strip() for p in bitrot_dirs if str(p).strip()),
        "mount_container_map": json.dumps(mount_map, ensure_ascii=False),
        "watch_targets": json.dumps(watch_targets, ensure_ascii=False),
        "switch_container_map": json.dumps(switch_map, ensure_ascii=False),
        "now": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
    }


def _project_root() -> Path:
    """项目根目录（scripts 的上级），跨平台无绝对路径硬编码。"""
    return Path(__file__).resolve().parent.parent


def main() -> None:
    parser = argparse.ArgumentParser(
        description="ZEN70 配置编译器（跨平台，路径均相对项目根）",
    )
    parser.add_argument(
        "config",
        nargs="?",
        default="system.yaml",
        help="system.yaml 路径（相对项目根），默认 system.yaml",
    )
    parser.add_argument(
        "-o", "--output-dir",
        default=".",
        help="输出目录（相对项目根），默认 .",
    )
    args = parser.parse_args()

    root = _project_root()
    config_path = root / args.config
    output_dir = root / args.output_dir
    templates_dir = Path(__file__).resolve().parent / "templates"

    if not config_path.exists():
        print(f"[ERROR] 配置不存在: {config_path}", file=sys.stderr)
        sys.exit(1)
    if not templates_dir.exists():
        print(f"[ERROR] 模板目录不存在: {templates_dir}", file=sys.stderr)
        sys.exit(1)

    # 1. config-lint
    config = config_lint(config_path)
    print("[config-lint] 校验通过")

    # 2. 逻辑聚合
    services_list = prepare_services(config)
    env_vars = prepare_env(config)
    # 幂等：用配置 mtime 作为时间戳，确保连续编译输出完全一致
    env_vars["now"] = datetime.fromtimestamp(
        config_path.stat().st_mtime, tz=timezone.utc
    ).strftime("%Y-%m-%d %H:%M:%S")

    # 2.5 防腐凭证中心：幂等解析，TUNNEL_TOKEN 缺失时注入占位符
    env_vars = generate_secrets(output_dir, env_vars)

    # 3. 渲染
    volumes_list = _extract_named_volumes(config)
    networks_list = _extract_networks(config)
    
    # 3.5 动态路由加载 (供 Routing-Operator 使用)
    dynamic_routes = []
    routes_file = root / "routes.json"
    if routes_file.exists():
        try:
            with routes_file.open("r", encoding="utf-8") as f:
                dynamic_routes = json.load(f)
        except Exception as e:
            print(f"[WARN] Failed to load routes.json: {e}", file=sys.stderr)
            
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(templates_dir)),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.globals["now"] = env_vars["now"]

    try:
        dc_tpl = env.get_template("docker-compose.yml.j2")
        dc_out = dc_tpl.render(
            services_list=services_list,
            volumes_list=volumes_list,
            networks_list=networks_list,
            now=env_vars["now"],
        )
    except jinja2.TemplateError as e:
        print(f"[ERROR] docker-compose 模板渲染失败: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        env_tpl = env.get_template(".env.j2")
        env_out = env_tpl.render(**env_vars)
    except jinja2.TemplateError as e:
        print(f"[ERROR] .env 模板渲染失败: {e}", file=sys.stderr)
        sys.exit(1)
        
    try:
        if (templates_dir / "Caddyfile.j2").exists():
            caddy_tpl = env.get_template("Caddyfile.j2")
            caddy_out = caddy_tpl.render(dynamic_routes=dynamic_routes)
        else:
            caddy_out = ""
    except jinja2.TemplateError as e:
        print(f"[ERROR] Caddyfile 模板渲染失败: {e}", file=sys.stderr)
        sys.exit(1)

    # 3.9 Redis 零信任 ACL 结界 (Phase 9)
    # 强制生成 users.acl 以实现内部权限物理隔离，避免特洛伊木马
    acl_content = f"""# 默认用户禁止登录并禁用危险指令
user default off nopass nocommands
# 后台边缘低权限只读账密，用于探针/挂载器
user readonly on >{secrets.token_urlsafe(16)} ~zen70:* &zen70:* +@read -@write +ping +info
# 核心网关全量特权
user zen70_gateway on >{env_vars['redis_password']} ~* &* +@all
"""
    config_dir = output_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "users.acl").write_text(acl_content, encoding="utf-8")

    # 4. Validate-Before-Commit 预检熔断 (Phase 9)
    output_dir.mkdir(parents=True, exist_ok=True)
    tmp_dc = output_dir / "docker-compose.yml.tmp"
    tmp_env = output_dir / ".env.tmp"
    
    tmp_dc.write_text(dc_out, encoding="utf-8")
    tmp_env.write_text(env_out, encoding="utf-8")
    
    print("[IaC-Validate] 正在执行 docker-compose config 预检...")
    import subprocess
    try:
        # 支持 docker-compose 或 docker compose 格式
        cmd = ["docker-compose", "--project-name", "zen70", "-f", str(tmp_dc), "--env-file", str(tmp_env), "config", "-q"]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0 and "No such file or directory" in res.stderr:
             # 回退到 docker compose v2
             cmd = ["docker", "compose", "--project-name", "zen70", "-f", str(tmp_dc), "--env-file", str(tmp_env), "config", "-q"]
             res = subprocess.run(cmd, capture_output=True, text=True)
             
        if res.returncode != 0:
            print(f"🔴 [ERROR] Validate-Before-Commit 免疫防御：预检失败，拒绝覆盖现有健康的 IaC 配置！\n详细信息:\n{res.stderr}", file=sys.stderr)
            tmp_dc.unlink(missing_ok=True)
            tmp_env.unlink(missing_ok=True)
            sys.exit(1)
            
        # 预检通过，实施原子替换封缄
        tmp_dc.replace(output_dir / "docker-compose.yml")
        tmp_env.replace(output_dir / ".env")
        env_path = output_dir / ".env"
        
    except Exception as e:
        print(f"🔴 [ERROR] 无法执行预检引擎调起: {e}", file=sys.stderr)
        tmp_dc.unlink(missing_ok=True)
        tmp_env.unlink(missing_ok=True)
        sys.exit(1)

    # 架构要求: 将 Caddyfile 写入到 config/ 目录内以备 Caddy 容器挂载
    if caddy_out:
        (config_dir / "Caddyfile").write_text(caddy_out, encoding="utf-8")
        
    try:
        os.chmod(env_path, 0o600)  # 仅所有者可读写（法典 7.1.2）
    except OSError:
        pass  # Windows 上可能无 chmod，忽略
    print(f"[OK] IaC 预检通过，已原位升维并生成 {output_dir / 'docker-compose.yml'}")
    print(f"[OK] 已生成 {env_path} (权限 600)")
    print(f"[OK] 已生成内部加密矩阵 {config_dir / 'users.acl'}")
    if caddy_out:
        print(f"[OK] 已生成 {config_dir / 'Caddyfile'}")


if __name__ == "__main__":
    main()
