#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
# AI-generated: 幂等部署器，支持增量更新与 --rollback 回滚（法典 6.9）
"""
ZEN70 上线后部署脚本：服务更新、配置重载、回滚恢复。

- 幂等：重复执行仅应用增量变更。
- --rollback：从 .zen70_backups 恢复上一健康快照并重载。
- 禁止用于 Day-0 裸机点火，仅限已上线系统的更新与回滚。
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------
BACKUP_DIR = ".zen70_backups"
DEFAULT_CONFIG = "system.yaml"


def _root() -> Path:
    return Path(__file__).resolve().parent.parent


def _scripts_dir() -> Path:
    return Path(__file__).resolve().parent


def _backup_state(root: Path, config_path: Path, output_dir: Path) -> Path:
    """将当前 system.yaml、docker-compose.yml、.env 备份到带时间戳目录。"""
    backup_base = root / BACKUP_DIR
    backup_base.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    dest = backup_base / ts
    dest.mkdir(parents=True, exist_ok=True)
    for name, src in [
        ("system.yaml", config_path),
        ("docker-compose.yml", output_dir / "docker-compose.yml"),
        (".env", output_dir / ".env"),
    ]:
        if src.exists():
            shutil.copy2(src, dest / name)
    return dest


def _list_backups(root: Path) -> list[Path]:
    """返回按时间倒序的备份目录列表。"""
    base = root / BACKUP_DIR
    if not base.exists():
        return []
    dirs = [d for d in base.iterdir() if d.is_dir()]
    dirs.sort(key=lambda p: p.name, reverse=True)
    return dirs


def _rollback(root: Path, output_dir: Path, backup_path: Path) -> None:
    """从备份目录恢复并执行 compose up。"""
    for name in ("system.yaml", "docker-compose.yml", ".env"):
        src = backup_path / name
        if not src.exists():
            print(f"[ERROR] 备份缺失: {name}", file=sys.stderr)
            sys.exit(1)
        dst = root / DEFAULT_CONFIG if name == "system.yaml" else output_dir / name
        shutil.copy2(src, dst)
        print(f"[OK] 已恢复 {name}")
    compose_file = output_dir / "docker-compose.yml"
    env = os.environ.copy()
    env.setdefault("COMPOSE_PROJECT_NAME", "zen70")
    r = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d", "--remove-orphans"],
        cwd=str(root),
        env=env,
        timeout=300,
    )
    if r.returncode != 0:
        print("[ERROR] docker compose up 失败", file=sys.stderr)
        sys.exit(1)
    print("[OK] 回滚完成")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="ZEN70 部署器（幂等，支持 --rollback 回滚）",
    )
    parser.add_argument(
        "--config",
        default=DEFAULT_CONFIG,
        help="system.yaml 路径，默认 system.yaml",
    )
    parser.add_argument(
        "-o", "--output-dir",
        default=None,
        help="编译输出目录，默认项目根",
    )
    parser.add_argument(
        "--rollback",
        action="store_true",
        help="回滚到上一备份快照",
    )
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="跳过本次部署前的备份（仅当确信可回滚时使用）",
    )
    args = parser.parse_args()

    root = _root()
    config_path = root / args.config if not Path(args.config).is_absolute() else Path(args.config)
    if args.output_dir:
        output_dir = Path(args.output_dir) if Path(args.output_dir).is_absolute() else root / args.output_dir
    else:
        output_dir = root

    if args.rollback:
        backups = _list_backups(root)
        if not backups:
            print("[ERROR] 无可用备份，无法回滚", file=sys.stderr)
            sys.exit(1)
        print(f"[INFO] 回滚到: {backups[0].name}")
        _rollback(root, output_dir, backups[0])
        return

    if not config_path.exists():
        print(f"[ERROR] 配置不存在: {config_path}", file=sys.stderr)
        sys.exit(1)

    if not args.no_backup:
        _backup_state(root, config_path, output_dir)
        print("[OK] 已备份当前状态")

    # 调用 compiler + compose up
    try:
        out_arg = "." if output_dir.resolve() == root.resolve() else str(output_dir.relative_to(root))
    except ValueError:
        out_arg = str(output_dir)
    cmd_compiler = [
        sys.executable,
        str(_scripts_dir() / "compiler.py"),
        str(config_path),
        "-o",
        out_arg,
    ]
    subprocess.run(cmd_compiler, cwd=str(root), check=True)
    compose_file = output_dir / "docker-compose.yml"
    env = os.environ.copy()
    env.setdefault("COMPOSE_PROJECT_NAME", "zen70")
    r = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d", "--remove-orphans"],
        cwd=str(root),
        env=env,
        timeout=300,
    )
    if r.returncode != 0:
        print("[ERROR] 部署失败，可使用 --rollback 恢复", file=sys.stderr)
        sys.exit(1)
    print("[OK] 部署完成")


if __name__ == "__main__":
    main()
