#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
# 法典 2.2：导出 OpenAPI 规范到 docs/openapi.json，纳入版本控制。
"""
从网关应用导出 OpenAPI 规范并写入 docs/openapi.json。
用法：在项目根目录执行 python scripts/export_openapi.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    sys.path.insert(0, str(root))
    try:
        from backend.main import app
    except ImportError as e:
        print(f"[ERROR] 无法导入 backend.main: {e}", file=sys.stderr)
        return 1
    out_path = root / "docs" / "openapi.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    schema = app.openapi()
    out_path.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[OK] 已写入 {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
