#!/usr/bin/env python3
# @generated by ZEN70-AI-Agent
# @architecture-version V2.0
# @compliance strict-sre-ruleset
# AI-generated: 法典 8.1.5 离线种子包与冷启动恢复 (Offline Seed)
"""
ZEN70 离线灾备种子导出工具
1. 解析 docker-compose.yml 提取镜像列表
2. 调用 docker save 将所有依赖镜像打包为离线 .tar 文件
3. 压缩当前配置档案 (system.yaml, .env) 与核心启动脚本 (bootstrap.py)
4. 生成 SHA256 完整性清单
"""

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tarfile
import yaml
from datetime import datetime
from pathlib import Path

def get_project_root() -> Path:
    return Path(__file__).resolve().parent.parent

def compute_sha256(file_path: Path) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

def extract_images(compose_file: Path) -> set[str]:
    """从 docker-compose.yml 提取全部需导出的 image tag"""
    if not compose_file.exists():
        print(f"[ERROR] 找不到编排文件 {compose_file}。请先运行 compiler.py", file=sys.stderr)
        sys.exit(1)
        
    try:
        data = yaml.safe_load(compose_file.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[ERROR] 解析 {compose_file} 失败: {e}", file=sys.stderr)
        sys.exit(1)
        
    images = set()
    services = data.get("services", {})
    for svc_name, svc_conf in services.items():
        if isinstance(svc_conf, dict) and "image" in svc_conf:
            image = str(svc_conf["image"]).strip()
            # 过滤掉自定义构建的未打标签镜像或变量替换残余
            if image and not image.startswith("${"):
                images.add(image)
    return images

def export_docker_images(images: set[str], output_tar: Path) -> bool:
    """调用 docker save 批量导出"""
    if not images:
        print("[WARN] 编排文件中未发现任何第三方外部镜像标签。")
        return True
        
    img_list = sorted(list(images))
    print(f"[INFO] 准备导出 {len(img_list)} 个镜像数据层...")
    for idx, img in enumerate(img_list):
        print(f"  [{idx+1}/{len(img_list)}] {img}")
        
    cmd = ["docker", "save", "-o", str(output_tar)] + img_list
    try:
        subprocess.run(cmd, check=True)
        print(f"[INFO] 镜像包已导出: {output_tar.stat().st_size / (1024**2):.2f} MB")
        return True
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] docker save 失败。请确保本地已有已拉取的镜像。 {e}", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("[ERROR] 找不到 docker 命令行工具。", file=sys.stderr)
        return False

def pack_offline_seed(root: Path, output_dir: Path) -> Path:
    """打包启动脚本与配置文件"""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    seed_name = f"zen70-offline-seed-{ts}"
    seed_dir = output_dir / seed_name
    seed_dir.mkdir(parents=True, exist_ok=True)
    
    # 核心资产复制
    assets = [
        "system.yaml", 
        "docker-compose.yml", 
        ".env",
        "scripts/bootstrap.py",
        "scripts/compiler.py",
        "scripts/requirements.txt",
        "scripts/templates"
    ]
    
    print("[INFO] 正在归档 ZEN70 控制平面凭证...")
    for asset in assets:
        src = root / asset
        if not src.exists():
            print(f"[WARN] 缺少源文件跳过: {asset}")
            continue
            
        dst = seed_dir / asset
        dst.parent.mkdir(parents=True, exist_ok=True)
        
        if src.is_file():
            shutil.copy2(src, dst)
        else:
            shutil.copytree(src, dst, dirs_exist_ok=True)
            
    # 导出镜像
    compose_file = root / "docker-compose.yml"
    images = extract_images(compose_file)
    tar_path = seed_dir / "images-bundle.tar"
    if not export_docker_images(images, tar_path):
        print("[ERROR] 镜像打包阻断。备份不完整。", file=sys.stderr)
        shutil.rmtree(seed_dir)
        sys.exit(1)

    # 封装备份 zip
    final_zip = output_dir / f"{seed_name}.zip"
    print(f"[INFO] 压缩离线种子包到: {final_zip}")
    # Python 内置 shutil.make_archive 跨平台压缩
    shutil.make_archive(str(output_dir / seed_name), 'zip', str(output_dir), seed_name)
    
    # 清理中间释放目录
    shutil.rmtree(seed_dir)
    return final_zip

def main():
    parser = argparse.ArgumentParser(description="ZEN70 第 0 天物理断网离线种子生成器")
    parser.add_argument("-o", "--output", default=".", help="输出目录 (默认为当前目录)")
    args = parser.parse_args()
    
    root = get_project_root()
    out_dir = Path(args.output).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    
    print("=== ZEN70 离线容灾打包程序 (法典 8.1.5) ===")
    zip_path = pack_offline_seed(root, out_dir)
    
    # 生成防篡改校验码
    sha = compute_sha256(zip_path)
    sha_file = zip_path.with_suffix(".sha256")
    sha_file.write_text(f"{sha} *{zip_path.name}\n", encoding="utf-8")
    
    print("\n[SUCCESS] 第 0 天冷启动备份已就绪。")
    print(f"产物: {zip_path}")
    print(f"校验: {sha_file}")
    print("请将其妥善复制至物理介质 (如加密 U 盘) 以备全断网恢复利用。")

if __name__ == "__main__":
    main()
