/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 */
import axios, { type AxiosInstance } from "axios";
import { getRequestId } from "./requestId";
import { useAuthStore } from "@/stores/auth";

const baseURL = import.meta.env.VITE_API_BASE_URL || "/api";

// Circuit Breaker State
export let isCircuitOpen = false;
let circuitBreakTimer: ReturnType<typeof setTimeout> | null = null;
const CIRCUIT_BREAKER_TIMEOUT = 15000; // 冷却期 15 秒

export const http: AxiosInstance = axios.create({
  baseURL,
  timeout: 10000,
});

http.interceptors.request.use((config) => {
  // 法典 6.2.3: 前端侧断路器，直接拦截请求，不发出
  if (isCircuitOpen) {
    return Promise.reject(new Error("Circuit Breaker OPEN: request dropped to protect backend."));
  }

  config.headers["X-Request-ID"] = getRequestId();
  const token = useAuthStore().token;
  if (token) config.headers.Authorization = `Bearer ${token}`;
  
  // 法典 3.5: AI 调度幂等性大闸
  if (config.url?.includes("/api/v1/ai") && ["post", "put"].includes(config.method?.toLowerCase() || "")) {
    config.headers["X-Idempotency-Key"] = crypto.randomUUID();
  }
  
  return config;
});

http.interceptors.response.use(
  (r) => {
    const newToken = r.headers["x-new-token"];
    if (typeof newToken === "string" && newToken) {
      useAuthStore().setToken(newToken);
    }
    return r;
  },
  (err) => {
    const newToken = err.response?.headers?.["x-new-token"];
    if (typeof newToken === "string" && newToken) {
      useAuthStore().setToken(newToken);
    }
    // 法典 2.5 & 3.3.1: 拦截 503 和 504 错误，进入悲观静默隔离
    if (err.response && (err.response.status === 503 || err.response.status === 504)) {
      if (!isCircuitOpen) {
        isCircuitOpen = true; // 触发熔断
        console.warn("[ZEN70 Circuit Breaker] OPEN - Hardware or Gateway Offline Detected");
        
        window.dispatchEvent(
          new CustomEvent("zen70-maintenance-mode", {
            detail: err.response.data,
          })
        );
        
        // 自动重置熔断器
        if (circuitBreakTimer) clearTimeout(circuitBreakTimer);
        circuitBreakTimer = setTimeout(() => {
          isCircuitOpen = false;
          console.info("[ZEN70 Circuit Breaker] CLOSED - Retrying resumes");
        }, CIRCUIT_BREAKER_TIMEOUT);
      }
    }

    console.error("[ZEN70] API error", {
      url: err.config?.url,
      status: err.response?.status,
      message: err.message,
    });
    return Promise.reject(err);
  }
);
