/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description 持久化存储申请
 * 调用 navigator.storage.persist() 防止浏览器清理 IndexedDB 数据
 */
export async function requestPersistentStorage(): Promise<boolean> {
  if (!("storage" in navigator) || !("persist" in navigator.storage)) {
    return false;
  }
  try {
    const granted = await navigator.storage.persist();
    if (!granted) {
      console.warn("[ZEN70 Warning] 离线灾备存储申请被拒绝，当前设备存储空间紧张时，离线缓存 (IndexedDB) 可能会被浏览器自动清理，部分断网能力可用性将受损！");
    } else {
      console.log("[ZEN70] Persistent storage granted:", granted);
    }
    return granted;
  } catch (_err) {
    return false;
  }
}

export async function isPersisted(): Promise<boolean> {
  if (!("storage" in navigator) || !("persisted" in navigator.storage)) {
    return false;
  }
  try {
    return await navigator.storage.persisted();
  } catch {
    return false;
  }
}
