/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 * @description SSE client with exp backoff (1s->2s->4s, max 30s), max 10 retries,
 * visibilitychange close on hidden, 503 no infinite loop.
 */
import type { HardwareEvent, SSEEvent, SwitchEvent, BoardEvent } from "@/types/sse";

const RECONNECT_BASE_MS = 1000;
const RECONNECT_MAX_MS = 30000;
const MAX_RETRIES = 10;

function parseData(e: MessageEvent): unknown {
  try {
    return typeof e.data === "string" ? JSON.parse(e.data) : e.data;
  } catch {
    return null;
  }
}

export type SSEOptions = {
  onFallbackOffline?: () => void;
};

/**
 * 创建 SSE 连接，订阅 hardware:events 和 switch:events。
 * 指数退避重连：1s->2s->4s... 上限 30s；最多 10 次后降级为离线骨架屏。
 * 页面 hidden 时关闭连接，防止僵尸句柄（V2.0 锁屏生命周期）。
 */
export function createSSE(
  url: string,
  onEvent: (ev: SSEEvent) => void,
  channels: ReadonlyArray<"hardware:events" | "switch:events" | "board:events"> = ["hardware:events", "switch:events", "board:events"],
  options: SSEOptions = {}
): () => void {
  let es: EventSource | null = null;
  let closed = false;
  let attempt = 0;

  function connect() {
    if (closed) return;
    if (attempt >= MAX_RETRIES) {
      options.onFallbackOffline?.();
      return;
    }
    es = new EventSource(url);

    for (const ch of channels) {
      es.addEventListener(ch, (e: MessageEvent) => {
        try {
          onEvent({ type: ch, data: parseData(e) as HardwareEvent | SwitchEvent | BoardEvent });
        } catch (err) {
          console.error(`[ZEN70] SSE parse ${ch}`, err);
        }
      });
    }

    es.addEventListener("connected", () => {
      attempt = 0;
    });

    es.onerror = () => {
      es?.close();
      es = null;
      if (closed) return;
      if (attempt >= MAX_RETRIES) {
        options.onFallbackOffline?.();
        return;
      }
      const delay = Math.min(RECONNECT_BASE_MS * 2 ** attempt, RECONNECT_MAX_MS);
      attempt += 1;
      setTimeout(connect, delay);
    };
  }

  function closeConnectionOnly() {
    es?.close();
    es = null;
  }

  function onVisibilityChange() {
    if (document.visibilityState === "hidden") {
      closeConnectionOnly();
    } else if (document.visibilityState === "visible" && !closed && !es) {
      attempt = 0;
      connect();
    }
  }

  document.addEventListener("visibilitychange", onVisibilityChange);
  connect();

  return () => {
    document.removeEventListener("visibilitychange", onVisibilityChange);
    closed = true;
    es?.close();
    es = null;
  };
}
