<template>
  <div class="max-w-4xl mx-auto py-6 relative">
    <!-- Header -->
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="font-bold flex items-center gap-3" :class="[auth.isElder ? 'text-5xl' : 'text-3xl']">
          <span class="text-4xl">🗼</span> 家族信标 (Family Board)
        </h1>
        <p class="opacity-60 mt-2" :class="[auth.isElder ? 'text-xl font-medium' : 'text-sm']">
          基于 SSE 的底层突触流，极速数字家庭交流。
        </p>
      </div>
      <button class="btn btn-outline shadow-xl hover:shadow-primary/30" :class="[auth.isElder ? 'btn-lg text-xl' : 'btn-sm']" @click="fetchMessages">
        🔄 手动快照
      </button>
    </div>

    <!-- 骨架屏 / Loading -->
    <div v-if="loading && messages.length === 0" class="flex flex-col gap-4">
      <div v-for="i in 3" :key="i" class="skeleton h-32 w-full rounded-2xl opacity-50"></div>
    </div>

    <!-- 发送区 -->
    <div class="card bg-base-100/60 backdrop-blur-xl border border-base-200 shadow-2xl mb-8">
      <div class="card-body p-4 sm:p-6">
        <textarea
          v-model="newContent"
          class="textarea textarea-bordered w-full bg-base-200/50 resize-y"
          :class="[auth.isElder ? 'text-2xl min-h-[160px] p-6' : 'textarea-lg min-h-[120px]']"
          placeholder="向家族广播..."
          :disabled="submitting"
        ></textarea>
        <div class="flex justify-between items-center mt-3">
          <div class="flex gap-2">
            <button class="btn btn-circle btn-sm btn-ghost tooltip" data-tip="附件 (建设中)">📎</button>
            <label class="label cursor-pointer hidden sm:flex gap-2">
              <span class="label-text">📍 置顶</span> 
              <input type="checkbox" v-model="isPinned" class="toggle toggle-primary toggle-sm" />
            </label>
          </div>
          <button class="btn btn-primary shadow-xl shadow-primary/30 min-w-[100px]" :class="[auth.isElder ? 'btn-lg text-xl' : '']" :disabled="submitting || !newContent.trim()" @click="postMessage">
            <span v-if="submitting" class="loading loading-spinner" :class="[auth.isElder ? 'loading-lg' : 'loading-sm']"></span>
            <span v-else>发射 🚀</span>
          </button>
        </div>
      </div>
    </div>

    <!-- 消息瀑布流 -->
    <TransitionGroup name="list" tag="div" class="flex flex-col gap-6 relative">
      <div 
        v-for="msg in messages" 
        :key="msg.id" 
        class="card bg-base-100 shadow-xl border border-base-200/50 hover:shadow-2xl transition-all duration-300"
        :class="{'border-l-4 border-l-primary': msg.is_pinned}"
      >
        <div class="card-body p-4 sm:p-6">
          <div class="flex justify-between items-start mb-2">
            <div class="flex items-center gap-3">
              <div class="avatar placeholder">
                <div class="bg-primary text-primary-content rounded-full w-10">
                  <span class="text-lg font-bold">{{ (msg.author?.display_name || msg.author?.username || '?')[0].toUpperCase() }}</span>
                </div>
              </div>
              <div>
                <p class="font-bold flex items-center gap-2" :class="[auth.isElder ? 'text-xl' : '']">
                  {{ msg.author?.display_name || msg.author?.username }}
                  <span v-if="msg.is_pinned" class="badge badge-primary badge-sm">置顶</span>
                </p>
                <p class="opacity-50" :class="[auth.isElder ? 'text-base font-medium' : 'text-xs']">{{ formatTime(msg.created_at) }}</p>
              </div>
            </div>
            
            <!-- 删除控制权限 (本人或 admin，童锁模式拦截) -->
            <button 
              v-if="(msg.author.username === auth.tokenPayload?.sub || auth.isAdmin) && !auth.isChild"
              class="btn btn-ghost btn-circle text-error opacity-40 hover:opacity-100 transition-opacity"
              :class="[auth.isElder ? 'btn-md text-xl' : 'btn-xs']"
              @click="deleteMessage(msg.id)"
              title="物理抹除"
            >
              ✕
            </button>
          </div>
          <p class="whitespace-pre-wrap mt-2 text-base-content/90" :class="[auth.isElder ? 'text-2xl font-medium leading-loose' : 'leading-relaxed']">{{ msg.content }}</p>
        </div>
      </div>
    </TransitionGroup>

    <div v-if="!loading && messages.length === 0" class="text-center py-20 opacity-50">
      <span class="text-6xl mb-4 block">📭</span>
      没有家族留言。去发射第一条吧。
    </div>

    <!-- 新消息 Toast 提示 (非本人发出时展示) -->
    <div class="toast toast-top toast-center z-50 pointer-events-none" v-if="showNewMsgToast">
      <div class="alert alert-info shadow-2xl backdrop-blur-md bg-info/80 text-info-content animate-bounce">
        <span>收到一条来自 {{ lastNewMsgAuthor }} 的神经突触...</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * @generated by ZEN70-AI-Agent
 * @architecture-version V2.0
 * @compliance strict-sre-ruleset
 */
import { ref, onMounted, onUnmounted } from "vue";
import { API_BASE } from "@/utils/api";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();

interface AuthorInfo {
  id: number;
  username: string;
  display_name?: string;
  role: string;
}

interface BoardMessage {
  id: string;
  content: string;
  meta_info?: any;
  is_pinned: boolean;
  created_at: string;
  author: AuthorInfo;
}

const messages = ref<BoardMessage[]>([]);
const loading = ref(false);
const submitting = ref(false);
const newContent = ref("");
const isPinned = ref(false);

const showNewMsgToast = ref(false);
const lastNewMsgAuthor = ref("");

function formatTime(isoStr: string) {
  const d = new Date(isoStr);
  return d.toLocaleString(undefined, {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit"
  });
}

// REST API 请求
async function fetchMessages() {
  loading.value = true;
  try {
    const res = await fetch(`${API_BASE}/v1/board`, {
      headers: { Authorization: `Bearer ${auth.token}` }
    });
    if (res.ok) {
      messages.value = await res.json();
    }
  } catch (err) {
    console.error("Failed to fetch messages", err);
  } finally {
    loading.value = false;
  }
}

async function postMessage() {
  if (!newContent.value.trim()) return;
  submitting.value = true;
  try {
    const res = await fetch(`${API_BASE}/v1/board`, {
      method: "POST",
      headers: { 
        "Content-Type": "application/json",
        Authorization: `Bearer ${auth.token}` 
      },
      body: JSON.stringify({
        content: newContent.value,
        is_pinned: isPinned.value
      })
    });
    if (res.ok) {
      const msg: BoardMessage = await res.json();
      messages.value.unshift(msg);
      newContent.value = "";
      isPinned.value = false;
    }
  } catch (err) {
    console.error("Failed to post message", err);
  } finally {
    submitting.value = false;
  }
}

async function deleteMessage(id: string) {
  if (!confirm("确定要物理抹除这条留言吗？(不可逆)")) return;
  try {
    const res = await fetch(`${API_BASE}/v1/board/${id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${auth.token}` }
    });
    if (res.ok) {
      messages.value = messages.value.filter(m => m.id !== id);
    }
  } catch (err) {
    console.error("Failed to delete message", err);
  }
}

// 监听全局 CustomEvent，由于 SSE 解析是全局 App.vue 内运行，我们可以让它抛事件出来
function handleSSEEvent(e: Event) {
  const ce = e as CustomEvent;
  if (!ce.detail || ce.detail.type !== "board:events") return;
  
  const payload = ce.detail.data;
  if (payload.action === "new_message") {
    // 收到新消息信号，无感拉取最新列表即可或者特定单个。这里为了简单，重新拉取最新列表静默合并。
    // 如果是自己发出的（页面中刚 unshift），前端列表里已经有了，避免重复拉。我们可以比对长度或静默拉取。
    fetchMessages();
    
    // 如果不是本人发的，闪现提示
    if (payload.author !== auth.tokenPayload?.sub && payload.author !== (auth.tokenPayload as any)?.display_name) {
      lastNewMsgAuthor.value = payload.author || "家族成员";
      showNewMsgToast.value = true;
      setTimeout(() => { showNewMsgToast.value = false; }, 4000);
    }
  } else if (payload.action === "delete_message" && payload.message_id) {
    messages.value = messages.value.filter(m => m.id !== payload.message_id);
  }
}

onMounted(() => {
  fetchMessages();
  // 我们需要在 App.vue 里把 SSE 的 board:events 分发成全局事件
  window.addEventListener("zen70-sse-board", handleSSEEvent);
});

onUnmounted(() => {
  window.removeEventListener("zen70-sse-board", handleSSEEvent);
});
</script>

<style scoped>
.list-enter-active, .list-leave-active {
  transition: all 0.5s ease;
}
.list-enter-from {
  opacity: 0;
  transform: translateY(-30px) scale(0.9);
}
.list-leave-to {
  opacity: 0;
  transform: translateX(100px);
}
</style>
